M48
; DRILL file KiCad 10.0.5 date 2026-08-18T11:50:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-18T11:50:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X7.5Y-2.3
X27.5Y-2.3
X47.5Y-2.3
X67.5Y-2.3
T2
X3.5Y-3.5
X3.5Y-38.5
X78.5Y-3.5
X78.5Y-38.5
M30
