M48
; DRILL file KiCad 10.0.5 date 2026-08-17T11:51:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T11:51:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X4.825Y-10.0
X11.175Y-10.0
T2
X2.5Y-2.5
X29.5Y-17.5
M30
