#!/usr/bin/env python3
"""Generate R255 Lot A supplier/metrology inquiry P0.2."""
from __future__ import annotations

import csv, hashlib, html, json, shutil
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"procurement/hr-v0/lot-a-inquiry-p0.2"
REL=ROOT/"release/hr-v0/lot-a-inquiry-p0.2"
CFG0=ROOT/"configuration/hr-v0-config-reconciliation-p0.18"
CFG=ROOT/"configuration/hr-v0-config-reconciliation-p0.19"
CFGR=ROOT/"release/hr-v0/configuration-reconciliation-p0.19"
ID="HR-V0-LOT-A-INQUIRY-P0.2"
WARNING="PRELIMINARY - NOT APPROVED FOR PROCUREMENT, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"

def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def read_csv(p:Path):
    with p.open(encoding="utf-8-sig",newline="") as f:
        r=csv.DictReader(f);return list(r),list(r.fieldnames or [])
def write_csv(p:Path,fields,rows):
    p.parent.mkdir(parents=True,exist_ok=True)
    with p.open("w",encoding="utf-8",newline="") as f:
        w=csv.DictWriter(f,fieldnames=fields,lineterminator="\n");w.writeheader();w.writerows({k:r.get(k,"") for k in fields} for r in rows)
def warned(rows):return [dict(r,warning=WARNING) for r in rows]
def manifest(d:Path):
    rows=[]
    for p in sorted(x for x in d.rglob("*") if x.is_file() and x.name!="file-manifest.csv"):
        rows.append({"path":p.relative_to(d).as_posix(),"bytes":p.stat().st_size,"sha256":sha(p)})
    write_csv(d/"file-manifest.csv",["path","bytes","sha256"],rows)
def table(title,rows,fields,filter_field=""):
    h="".join(f"<th>{html.escape(x.replace('_',' ').title())}</th>" for x in fields)
    b="".join(f'<tr data-route="{html.escape(str(r.get(filter_field,"")))}">'+"".join(f"<td>{html.escape(str(r.get(x,'')))}</td>" for x in fields)+"</tr>" for r in rows)
    return f"<section><h2>{html.escape(title)}</h2><div class=scroll><table><thead><tr>{h}</tr></thead><tbody>{b}</tbody></table></div></section>"
def guide(routes,trans,robotis,metro,bids,evidence,gates,workflow):
    buttons="".join(f'<button data-filter="{r["route_id"]}">{r["route_id"]}</button>' for r in routes)
    return f"""<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>HR-V0 Lot A inquiry P0.2</title><style>
:root{{--sky:#dff3ff;--blue:#092f57;--gold:#f4bd27;--ink:#102338;--paper:#f8fbfe;--line:#8eb9d8}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:clamp(16px,1.15vw,19px)/1.55 system-ui,sans-serif}}header{{padding:clamp(24px,5vw,68px);background:linear-gradient(135deg,var(--sky),#fff);border-bottom:8px solid var(--gold)}}main{{max-width:1500px;margin:auto;padding:24px}}h1{{font-size:clamp(34px,5vw,72px);line-height:1.05;color:var(--blue);margin:.2em 0}}h2{{color:var(--blue);font-size:clamp(24px,2.4vw,36px)}}.warn{{background:#fff4c7;border:3px solid var(--gold);padding:16px;font-weight:800}}.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;margin:24px 0}}.card,section{{background:#fff;border:2px solid var(--line);border-radius:14px;padding:18px;margin:18px 0}}.big{{font-size:2rem;font-weight:800;color:var(--blue)}}button{{font:inherit;font-weight:750;padding:10px 14px;margin:5px;border:2px solid var(--blue);border-radius:999px;background:#fff;color:var(--blue)}}button.active{{background:var(--blue);color:#fff}}.scroll{{overflow:auto}}table{{width:100%;border-collapse:collapse;min-width:880px;font-size:14px}}th,td{{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #bed5e6}}th{{background:var(--blue);color:#fff;position:sticky;top:0}}.note{{font-size:14px}}@media(max-width:700px){{main{{padding:12px}}}}</style></head><body><header><p class=warn>{WARNING}</p><h1>Lot A inquiry P0.2</h1><p>Controlled drafts for supplier identity and task-specific metrology bids. Nothing sent. Nothing ordered.</p></header><main><div class=cards><div class=card><div class=big>5</div>inquiry routes</div><div class=card><div class=big>44</div>controlled questions</div><div class=card><div class=big>0</div>responses received</div><div class=card><div class=big>0</div>send or purchase authorizations</div></div><section><h2>Filter inquiry routes</h2><button class=active data-filter=ALL>All</button>{buttons}<p class=note>Filtering is a review aid only. It cannot transmit a message or authorize contact.</p></section>
{table('Inquiry routes',routes,['route_id','organization','official_route','purpose','route_state','selection_state'],'route_id')}{table('Transmission control',trans,['transmittal_id','route_id','message_path','message_sha256','attachment_set','send_authorization','sent_state'],'route_id')}{table('ROBOTIS questions',robotis,['question_id','route_id','category','question','required_evidence','state'],'route_id')}{table('Metrology questions',metro,['question_id','route_id','method_id','category','question','required_evidence','state'],'route_id')}{table('Method bid schedule',bids,['bid_id','route_id','method_id','requested_scope','bid_state','technical_disposition'],'route_id')}{table('Required returned evidence',evidence,['evidence_id','route_id','required_record','acceptance_boundary','state'],'route_id')}{table('Decision gates',gates,['gate_id','decision','evidence_required','owner_role','state'])}{table('Workflow',workflow,['step_id','action','entry_gate','output','authorization','execution_state'])}<section><h2>Boundary</h2><p>The drafts contain no private ship-to address, payment data or personal sender identity. Those fields remain selection required. Sending, purchasing, shipping and work each require separate written authority. Provider capability claims are not method acceptance.</p></section></main><script>const bs=[...document.querySelectorAll('button[data-filter]')];bs.forEach(b=>b.onclick=()=>{{bs.forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('tr[data-route]').forEach(r=>r.hidden=f!=='ALL'&&r.dataset.route!==f)}});</script></body></html>"""

def main():
    for d in (OUT,REL,CFG,CFGR):
        if d.exists():shutil.rmtree(d)
    OUT.mkdir(parents=True)
    routes=[
      {"route_id":"R255-RT-01","organization":"ROBOTIS America sales/orders","official_route":"america@robotis.com; 949-377-0377 ext. 1","purpose":"Written model/SKU/contents/stock/quote/shipping response","route_state":"CURRENT OFFICIAL CONTACT RECHECKED 2026-08-11","selection_state":"NOT AUTHORIZED TO CONTACT"},
      {"route_id":"R255-RT-02","organization":"ROBOTIS technical support","official_route":"cs@robotis.com; 949-377-0377","purpose":"Written technical document/assembly-hardware response","route_state":"CURRENT OFFICIAL SUPPORT CONTACT RECHECKED 2026-08-11","selection_state":"NOT AUTHORIZED TO CONTACT"},
      {"route_id":"R255-RT-03","organization":"East Coast Metrology / ECM, Topsfield MA","official_route":"info@eastcoastmetrology.com; 978-887-5781","purpose":"Primary task-specific dimensional/CMM/scan/angle/mass capability and quote inquiry","route_state":"OFFICIAL SERVICE/CONTACT RECORD RECHECKED 2026-08-11","selection_state":"RESEARCH CANDIDATE - NOT SELECTED OR CONTACTED"},
      {"route_id":"R255-RT-04","organization":"3D ProScan, Clinton MA","official_route":"https://www.3dproscan.com/metrology-services.html; 978-365-8164","purpose":"Alternate dimensional/CMM/scan/mass capability and quote inquiry","route_state":"OFFICIAL SERVICE/CONTACT RECORD RECHECKED 2026-08-11","selection_state":"RESEARCH CANDIDATE - NOT SELECTED OR CONTACTED"},
      {"route_id":"R255-RT-05","organization":"Celero Partners, Woburn MA","official_route":"info@celeropartners.com; 781-618-4977","purpose":"Scan-only/geometry-data capability and quote inquiry; no CMM or accreditation inferred","route_state":"OFFICIAL COMPANY/CONTACT RECORD RECHECKED 2026-08-11","selection_state":"RESEARCH CANDIDATE - NOT SELECTED OR CONTACTED"},
    ]
    robotis_q=[
      ("01","R255-RT-01","IDENTITY","Does SKU 902-0137-000 currently ship exactly XM540-W270-T with TTL communication despite the same product page package table naming XM540-W270-R?","Dated written SKU-to-model-to-protocol binding"),
      ("02","R255-RT-01","IDENTITY","State the model label, hardware revision and country of origin that would ship for two units of SKU 902-0137-000.","Written identity/revision/origin list"),
      ("03","R255-RT-01","CONTENTS","List every cable, screw, washer, spacer, horn/frame item and other included article for each of the three requested order codes.","Order-code-specific contents list"),
      ("04","R255-RT-01","ALLOCATION","Confirm whether two units each of 902-0137-000, 903-0270-300 and 903-0269-300 can be allocated and state lead time.","Dated allocation and lead-time statement"),
      ("05","R255-RT-01","QUOTE","Provide an itemized quotation to Boston, Massachusetts for quantities 2/2/2, including shipping estimate, tax treatment, fees and expiration; final ship-to address is withheld pending authorization.","Dated quote; no checkout or order"),
      ("06","R255-RT-01","CONDITION","Confirm all six articles would be new, manufacturer-labeled and accompanied by traceable packing records.","Written condition and traceability statement"),
      ("07","R255-RT-01","SUBSTITUTION","Confirm no -R actuator, alternate protocol, alternate frame/horn or substituted order code will ship without written buyer acceptance.","Written no-substitution acknowledgement"),
      ("08","R255-RT-01","SHIPPING","State domestic insurance/signature options and the applicable return/RMA terms for unopened, misidentified or damaged articles.","Written shipping/return terms or official policy reference"),
      ("09","R255-RT-02","ASSEMBLY","Identify the current official X540/H101/S102 assembly documents and their revision/date.","Official document links and revision/date"),
      ("10","R255-RT-02","HARDWARE","State published screw designations, maximum mounting depths, spacer/thrust-washer placement, strength class and coating for this exact stack, or explicitly identify each item not specified.","Official document references or explicit not-specified response"),
      ("11","R255-RT-02","TORQUE","Is there a manufacturer-published temporary-assembly torque, locking-compound and screw-reuse instruction for this exact stack? Do not estimate.","Official document reference or explicit statement no value is supplied"),
      ("12","R255-RT-02","BOUNDARY","Confirm the responder name/role, response date and whether the answer is manufacturer-authorized technical guidance.","Dated attributable written response"),
    ]
    robotis=[{"question_id":f"R255-RQ-{n}","route_id":rt,"category":c,"question":q,"required_evidence":e,"state":"UNSENT / NOT RECEIVED"} for n,rt,c,q,e in robotis_q]
    general=[
      ("G01","IDENTITY","State legal provider name, performing facility and responsible technical contact.","Attributable written response"),("G02","SCOPE","State BID or NO BID for each M01-M05 method; do not bundle unbid methods.","Completed method bid schedule"),("G03","BOUNDARY","Acknowledge unpowered/unconnected work, no encoder access and no fabrication/safety/energization approval.","Signed boundary acknowledgement"),("G04","CHAIN","Describe receiving, quarantine, segregation, photos, custody, insurance and return controls.","Controlled chain-of-custody plan"),("G05","EQUIPMENT","List proposed equipment by maker/model/serial, software/version and performing facility.","Equipment register"),("G06","CALIBRATION","Provide calibration certificates/due dates/traceability for every result-producing instrument and artifact.","Current certificates and traceability chain"),("G07","ACCREDITATION","Provide current ISO/IEC 17025 certificate/scope and map each quoted result inside or outside scope; ISO 9001 alone is not sufficient.","Certificate, scope and result map"),("G08","SUBCONTRACT","Identify every subcontracted activity, facility and data transfer.","Subcontractor disclosure"),("G09","DATA","Confirm native/raw files, CSV results, transforms, residuals, processing logs, scale-bearing photos and SHA-256-compatible delivery.","Deliverable list and sample/redacted format"),("G10","UNCERTAINTY","Provide method-specific uncertainty budgets, coverage factors, distributions, sensitivities and reporting rule; do not substitute resolution for uncertainty.","Method uncertainty proposals"),("G11","COMMERCIAL","Price methods separately with fixed/not-to-exceed assumptions, fixture development, shipping, insurance, tax, witness, lead time and expiration.","Itemized quote"),("G12","STOP WORK","Describe discrepancy, damage, unexpected contact/force, nonconformance, stop-work and quarantine rules.","Controlled nonconformance workflow"),
    ]
    specific={
      "JSM2-M01":[("01","METHOD","Propose loose-part depth/face/feature-coordinate measurands and datum construction without inferring thread function.","Drawing/method proposal"),("02","SUPPORT","Propose nonmarring free-state support and prove measured features remain accessible and unbiased.","Support sketch and reseat plan"),("03","REPEAT","Define probe strategy, reseat/repeat series, environmental controls and raw point retention.","Repeatability/environment plan"),("04","OUTPUT","State deliverable coordinate system, point/features, fit algorithms, residuals and uncertainty.","M01 output specification")],
      "JSM2-M02":[("01","AXIS","Propose external construction of the output-to-idler joint axis from exact received features/artifacts and state fit algorithms/residuals.","Axis-realization method"),("02","ASSEMBLY","Acknowledge no screw insertion until a separately signed exact hardware/torque/reuse instruction is supplied.","Signed assembly hold"),("03","SUPPORT","Propose support/restraint leaving outer faces and axis features accessible without loading case, connector or unapproved threads.","Support/access sketch"),("04","OUTPUT","Define axial measurands, transforms, repetitions and uncertainty.","M02 output specification")],
      "JSM2-M03":[("01","ANGLE","Propose calibrated external angle reference; actuator encoder data are prohibited.","External reference method"),("02","RESTRAINT","Propose independent gravity restraint/counterbalance and allowed operator-force measurement.","Restraint/force method"),("03","CYCLE","Define bidirectional hand-position sequence, repetitions, reversal rule and stop-work force threshold.","Cycle protocol"),("04","OUTPUT","Define backlash estimator, raw angles/forces, hysteresis representation and uncertainty.","M03 output specification")],
      "JSM2-M04":[("01","SCANNER","State scanner/model/serial, point spacing, verified volumetric error and calibration artifact over this article size.","Scanner capability evidence"),("02","OCCLUSION","Propose at least two low-occlusion orientations and supports; the P0.2 frame may not be the sole fixture.","Pose/support plan"),("03","REGISTRATION","Define fiducials/reference artifact, transform chain, registration algorithm, residual reporting and independent check.","Registration validation plan"),("04","OUTPUT","Provide raw scans/point clouds, trimmed/untrimmed data, meshes, transforms, logs and screening-only uncertainty.","M04 output specification")],
      "JSM2-M05":[("01","BALANCE","State balance maker/model/serial, range, resolution, calibration and location.","Balance capability evidence"),("02","TARE","Define tray/container tare, stability, zero checks and air-current/temperature controls.","Tare/environment method"),("03","IDENTITY","Define loose-article and frozen assembled-stack identity/repetition records.","Mass identity/repeat plan"),("04","OUTPUT","Provide raw readings, corrections, repetitions and uncertainty in grams.","M05 output specification")],
    }
    metro=[]
    for rt in ("R255-RT-03","R255-RT-04","R255-RT-05"):
      for n,c,q,e in general:metro.append({"question_id":f"R255-MQ-{rt[-2:]}-{n}","route_id":rt,"method_id":"ALL","category":c,"question":q,"required_evidence":e,"state":"UNSENT / NOT RECEIVED"})
      for method,qs in specific.items():
        for n,c,q,e in qs:metro.append({"question_id":f"R255-MQ-{rt[-2:]}-{method[-3:]}-{n}","route_id":rt,"method_id":method,"category":c,"question":q,"required_evidence":e,"state":"UNSENT / NOT RECEIVED"})
    # 32 unique questions are repeated per provider so every response is independently attributable.
    bid_scope={"JSM2-M01":"Loose-part CMM/contact dimensions","JSM2-M02":"Assembled axial stack and external axis realization","JSM2-M03":"External unpowered angle/backlash","JSM2-M04":"Low-occlusion multi-orientation scan","JSM2-M05":"Loose and assembled mass"}
    bids=[{"bid_id":f"R255-BID-{rt[-2:]}-{m[-3:]}","route_id":rt,"method_id":m,"requested_scope":s,"bid_state":"NOT RECEIVED","technical_disposition":"NOT EXECUTED"} for rt in ("R255-RT-03","R255-RT-04","R255-RT-05") for m,s in bid_scope.items()]
    robotis_msg=f"""# UNSENT ROBOTIS Lot A clarification and quote request\n\n> **{WARNING}**\n\nProject Button requests written answers to `R255-RQ-01..12` for a possible evaluation-only purchase of two each: SKU `902-0137-000`, `903-0270-300`, and `903-0269-300`. The product-page `XM540-W270-T` title/TTL/SKU versus `XM540-W270-R` package-table conflict must be resolved in writing.\n\nPlease return attributable, dated responses and official document links. Do not create an order, reserve stock, ship, substitute, or treat this request as purchase authority. Quote destination is Boston, Massachusetts; the final address and payment data are intentionally withheld pending separate authorization.\n\nThis message is **UNSENT**. Sender identity and reply address are `SELECTION REQUIRED`.\n"""
    metro_msg=f"""# UNSENT HR-V0 task-specific metrology capability and quote request\n\n> **{WARNING}**\n\nProject Button requests an information-only capability response and separately itemized bid for `JSM2-M01..M05`. Six exact ROBOTIS articles may be acquired later, but none is currently ordered or available for shipment. Providers may answer BID or NO BID per method.\n\nNo source, actuator cable, U2D2, encoder access, powered operation, motion, or design approval is permitted. No threaded assembly is permitted without a later signed, exact hardware/torque/reuse instruction. Return the provider-specific `R255-MQ-*` responses, method bid schedule, supporting certificates/scopes, method sketches, uncertainty proposals and itemized commercial quote.\n\nThis request is not an order or work authorization. Do not begin fixture design, receive articles, subcontract work, or incur cost without a later configuration-specific signed authorization. Sender identity and reply address are `SELECTION REQUIRED`.\n"""
    (OUT/"UNSENT-robotis-request.md").write_text(robotis_msg,encoding="utf-8")
    (OUT/"UNSENT-metrology-request.md").write_text(metro_msg,encoding="utf-8")
    attachments=[
      {"attachment_id":"R255-AT-01","path":"docs/hr-v0-joint-stack-metrology-p0.2.md","sha256":sha(ROOT/"docs/hr-v0-joint-stack-metrology-p0.2.md"),"recipient_scope":"METROLOGY","release_boundary":"Planning requirements only"},
      {"attachment_id":"R255-AT-02","path":"release/hr-v0/joint-stack-metrology-p0.2/method-register.csv","sha256":sha(ROOT/"release/hr-v0/joint-stack-metrology-p0.2/method-register.csv"),"recipient_scope":"METROLOGY","release_boundary":"Five unexecuted methods"},
      {"attachment_id":"R255-AT-03","path":"release/hr-v0/joint-stack-metrology-p0.2/hsi-method-map.csv","sha256":sha(ROOT/"release/hr-v0/joint-stack-metrology-p0.2/hsi-method-map.csv"),"recipient_scope":"METROLOGY","release_boundary":"Open evidence routes only"},
      {"attachment_id":"R255-AT-04","path":"release/hr-v0/joint-stack-metrology-p0.2/uncertainty-input-register.csv","sha256":sha(ROOT/"release/hr-v0/joint-stack-metrology-p0.2/uncertainty-input-register.csv"),"recipient_scope":"METROLOGY","release_boundary":"Blank input scaffold; no accepted budget"},
    ]
    response_templates=[]
    for route in routes:
      rt=route["route_id"]
      if rt in {"R255-RT-01","R255-RT-02"}:
        subset=[dict(r,provider_response="",response_evidence_uri="",reviewer_disposition="NOT EXECUTED") for r in robotis if r["route_id"]==rt]
        name=f"response-template-{rt}.csv"
        write_csv(OUT/name,list(subset[0]),subset)
      else:
        subset=[dict(r,provider_response="",response_evidence_uri="",reviewer_disposition="NOT EXECUTED") for r in metro if r["route_id"]==rt]
        name=f"response-template-{rt}.csv"
        write_csv(OUT/name,list(subset[0]),subset)
      response_templates.append({"template_id":f"R255-RSP-{rt[-2:]}","route_id":rt,"path":name,"sha256":sha(OUT/name),"response_rows":len(subset),"response_state":"BLANK / NOT RECEIVED"})
    trans=[]
    for i,r in enumerate(routes,1):
      msg="UNSENT-robotis-request.md" if i<=2 else "UNSENT-metrology-request.md"
      response_id=f"R255-RSP-{r['route_id'][-2:]}"
      trans.append({"transmittal_id":f"R255-TX-{i:02d}","route_id":r["route_id"],"message_path":msg,"message_sha256":sha(OUT/msg),"attachment_set":response_id if i<=2 else f"R255-AT-01..04 + {response_id} + ROUTE-SCOPED BID ROWS","sender_identity":"SELECTION REQUIRED","reply_address":"SELECTION REQUIRED","send_authorization":"NOT AUTHORIZED","sent_state":"NOT SENT"})
    evidence_specs=[
      ("01","R255-RT-01","SKU/model/protocol response","Attributable date and exact three-way binding"),("02","R255-RT-01","Contents/revision/origin response","Every requested order code covered"),("03","R255-RT-01","Allocation and complete quote","Dated, itemized and unexpired"),("04","R255-RT-01","Shipping/return/no-substitution response","Terms accepted before purchase"),("05","R255-RT-02","Official assembly-document response","Revision/date and exact applicability"),("06","R255-RT-02","Hardware/torque/locking/reuse response","No inferred value; omissions explicit"),
      ("07","METROLOGY","Legal identity and performing facility","Attributable provider response"),("08","METROLOGY","Method BID/NO BID schedule","All M01-M05 answered separately"),("09","METROLOGY","Equipment/software register","Maker/model/serial/version/facility"),("10","METROLOGY","Calibration certificates","Current, traceable, result-mapped"),("11","METROLOGY","ISO/IEC 17025 certificate and scope map","Exact results marked in/out of scope"),("12","METROLOGY","Method/support/datum proposals","Method-specific and non-damaging"),("13","METROLOGY","Uncertainty budgets","Inputs, distributions, sensitivities, coverage"),("14","METROLOGY","Raw-data/deliverable proposal","Native files, transforms, residuals, logs, photos"),("15","METROLOGY","Commercial quote","Separate methods, assumptions, shipping/tax/insurance/expiration"),("16","METROLOGY","Boundary acknowledgement","Unpowered/no authority signed"),("17","METROLOGY","Chain/nonconformance/return plan","Article identity and quarantine preserved"),("18","ALL","Qualified bid disposition","Independent technical acceptance; no work authority")]
    evidence=[{"evidence_id":f"R255-EV-{n}","route_id":rt,"required_record":rec,"acceptance_boundary":b,"state":"NOT RECEIVED"} for n,rt,rec,b in evidence_specs]
    gate_specs=[
      ("01","Authorize each external inquiry transmission","Exact message/attachments hashes, recipient route, sender/reply identity, program-owner approval","PROGRAM OWNER"),("02","Resolve XM540 -T/-R identity","Accepted R255-RQ-01/02 response","CONFIGURATION + ELECTRICAL"),("03","Accept no-substitution and contents","Accepted R255-RQ-03/06/07 response","CONFIGURATION + MECHANICAL"),("04","Accept current allocation and quote","Unexpired response/quote","PROCUREMENT"),("05","Set maximum purchase spend","Numerical signed limit","PROGRAM OWNER"),("06","Freeze ship-to/receiver/quarantine","Named adult receiver and controlled location","PROGRAM OWNER"),("07","Authorize receipt-only purchase","Exact commit, lines, seller, quote, maximum spend, exclusions","PROGRAM OWNER"),("08","Receive and reconcile six articles","Labels, lots, contents, photos, discrepancies","RECEIVING + CONFIGURATION"),("09","Accept provider identity/scope","Complete attributable response and bid map","METROLOGY"),("10","Accept equipment/calibration/accreditation","Certificates and result scope map","QUALIFIED METROLOGY REVIEWER"),("11","Accept method-specific supports/datums","M01-M05 technical proposals independently reviewed","QUALIFIED MECHANICAL/METROLOGY REVIEWER"),("12","Accept method-specific uncertainty budgets","Numeric budgets and validation evidence","QUALIFIED METROLOGY REVIEWER"),("13","Select provider and commercial scope","Technical acceptance plus program-owner commercial decision","PROGRAM OWNER + QUALIFIED REVIEWER"),("14","Authorize shipment/work","Configuration-specific scope, articles, methods, witnesses, stop conditions","PROGRAM OWNER + QUALIFIED REVIEWER"),("15","Authorize temporary threaded assembly","Exact manufacturer/engineering hardware instruction and separate work authority","QUALIFIED MECHANICAL REVIEWER")]
    gates=[{"gate_id":f"R255-GT-{n}","decision":d,"evidence_required":e,"owner_role":o,"state":"OPEN"} for n,d,e,o in gate_specs]
    workflow_specs=[("01","Freeze exact inquiry package hashes","GT-01","Controlled transmittal record"),("02","Authorize and send sales/order inquiry","GT-01","Attributable ROBOTIS sales response"),("03","Authorize and send technical inquiry","GT-01","Attributable ROBOTIS technical response"),("04","Ingest and hash ROBOTIS responses","GT-02","Immutable evidence records"),("05","Independently disposition identity/technical responses","GT-02/03","Accepted/rejected finding register"),("06","Authorize and send provider-specific metrology inquiries","GT-01","Attributable provider responses"),("07","Ingest and hash provider bids/certificates","GT-09","Immutable evidence records"),("08","Technical bid evaluation by method","GT-10/11/12","Method-specific disposition"),("09","Commercial bid evaluation","GT-13","Selected or no-award decision"),("10","Authorize exact purchase or no-buy","GT-02..07","Signed purchase decision"),("11","Receive and quarantine articles","GT-07","Received configuration record"),("12","Authorize loose metrology only","GT-08..12","Method-specific work order"),("13","Close assembly instruction","GT-15","Signed instruction"),("14","Authorize later assembled methods","GT-13..15","Method-specific work order")]
    workflow=[{"step_id":f"R255-WF-{n}","action":a,"entry_gate":g,"output":o,"authorization":"NONE","execution_state":"NOT EXECUTED"} for n,a,g,o in workflow_specs]
    acceptance=[{"acceptance_id":f"R255-ACC-{i:02d}","criterion":g["decision"],"execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":""} for i,g in enumerate(gates,1)]
    sources=[
      {"source_id":"R255-SRC-01","authority":"Project Button","title":"Lot A source reconciliation P0.1","revision_or_date":"2026-08-11 controlled predecessor","path_or_url":"docs/hr-v0-lot-a-source-reconciliation-p0.1.md","sha256":sha(ROOT/"docs/hr-v0-lot-a-source-reconciliation-p0.1.md"),"controlled_fact":"Historical article identity/conflict and eight unsent questions"},
      {"source_id":"R255-SRC-02","authority":"Project Button","title":"Evaluation acquisition/metrology P0.1","revision_or_date":"2026-08-08 controlled predecessor","path_or_url":"docs/hr-v0-evaluation-acquisition-metrology-p0.1.md","sha256":sha(ROOT/"docs/hr-v0-evaluation-acquisition-metrology-p0.1.md"),"controlled_fact":"Historical provider screen and RFQ questions"},
      {"source_id":"R255-SRC-03","authority":"Project Button","title":"Joint-stack metrology P0.2","revision_or_date":"R254 / 2026-08-11","path_or_url":"docs/hr-v0-joint-stack-metrology-p0.2.md","sha256":sha(ROOT/"docs/hr-v0-joint-stack-metrology-p0.2.md"),"controlled_fact":"Current five-method execution boundary"},
      {"source_id":"R255-SRC-04","authority":"ROBOTIS","title":"Support","revision_or_date":"live official page rechecked 2026-08-11","path_or_url":"https://www.robotis.us/Support","sha256":"","controlled_fact":"cs@robotis.com; 949-377-0377; published typical response time"},
      {"source_id":"R255-SRC-05","authority":"ROBOTIS","title":"Contact Us","revision_or_date":"live official page rechecked 2026-08-11","path_or_url":"https://www.robotis.us/contact-us/","sha256":"","controlled_fact":"america@robotis.com; 949-377-0377"},
      {"source_id":"R255-SRC-06","authority":"ROBOTIS","title":"Shipping, Returns, and Warranty","revision_or_date":"live official policy rechecked 2026-08-11","path_or_url":"https://www.robotis.us/shipping-returns-warranty/","sha256":"","controlled_fact":"Domestic insurance/request and return/RMA policy route; exact transaction terms still require response"},
      {"source_id":"R255-SRC-07","authority":"East Coast Metrology","title":"Measurement Services","revision_or_date":"live official page rechecked 2026-08-11","path_or_url":"https://eastcoastmetrology.com/services/","sha256":"","controlled_fact":"Topsfield service/contact and CMM/scan claims; no project method acceptance inferred"},
      {"source_id":"R255-SRC-08","authority":"East Coast Metrology","title":"CMM Measurement Services","revision_or_date":"live official page rechecked 2026-08-11","path_or_url":"https://eastcoastmetrology.com/lp/cmm-measurement-services/","sha256":"","controlled_fact":"CMM/noncontact capability claims; equipment/uncertainty/scope require bid response"},
      {"source_id":"R255-SRC-09","authority":"3D ProScan","title":"Metrology Services","revision_or_date":"live official page rechecked 2026-08-11","path_or_url":"https://www.3dproscan.com/metrology-services.html","sha256":"","controlled_fact":"Clinton contact and published CMM/vision/balance capabilities; ISO 9001 is not ISO/IEC 17025"},
      {"source_id":"R255-SRC-10","authority":"Celero Partners","title":"Company and scanning services","revision_or_date":"live official page rechecked 2026-08-11","path_or_url":"https://celeropartners.com/","sha256":"","controlled_fact":"Woburn contact and scanning claim; no CMM/traceability/uncertainty inferred"},
      {"source_id":"R255-SRC-11","authority":"NIST","title":"Technical Note 1297","revision_or_date":"1994 edition; official page rechecked 2026-08-11","path_or_url":"https://www.nist.gov/pml/nist-technical-note-1297","sha256":"","controlled_fact":"Uncertainty component/combination/reporting route"},
    ]
    outputs={
      "inquiry-route-register.csv":(list(routes[0])+["warning"],warned(routes)),"transmittal-register.csv":(list(trans[0])+["warning"],warned(trans)),"response-template-register.csv":(list(response_templates[0])+["warning"],warned(response_templates)),"robotis-question-register.csv":(list(robotis[0])+["warning"],warned(robotis)),"metrology-question-register.csv":(list(metro[0])+["warning"],warned(metro)),"method-bid-schedule.csv":(list(bids[0])+["warning"],warned(bids)),"attachment-manifest.csv":(list(attachments[0])+["warning"],warned(attachments)),"returned-evidence-register.csv":(list(evidence[0])+["warning"],warned(evidence)),"decision-gate.csv":(list(gates[0])+["warning"],warned(gates)),"workflow-register.csv":(list(workflow[0])+["warning"],warned(workflow)),"acceptance-matrix.csv":(list(acceptance[0])+["warning"],warned(acceptance)),"source-register.csv":(list(sources[0])+["warning"],warned(sources))}
    for n,(f,r) in outputs.items():write_csv(OUT/n,f,r)
    status={"identifier":ID,"round":"R255","date":"2026-08-11","inquiry_routes":5,"unique_question_definitions":44,"provider_attributed_metrology_question_rows":96,"robotis_question_rows":12,"method_bid_rows":15,"returned_evidence_rows":18,"decision_gates":15,"workflow_steps":14,"responses_received":0,"transmissions_authorized":0,"messages_sent":0,"provider_selected":False,"purchase_authorized":False,"order_placed":False,"shipment_authorized":False,"work_authorized":False,"physical_articles_received":False,"qualified_review_complete":False,"assembly_authorized":False,"connection_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False,"warning":WARNING}
    (OUT/"package-status.json").write_text(json.dumps(status,indent=2)+"\n",encoding="utf-8")
    (OUT/"index.html").write_text(guide(routes,trans,robotis,metro,bids,evidence,gates,workflow),encoding="utf-8")
    manifest(OUT);shutil.copytree(OUT,REL);manifest(REL)

    shutil.copytree(CFG0,CFG)
    current,cf=read_csv(CFG/"current-configuration-map.csv");current.append({"record_id":"CFG-38","role":"Lot A supplier identity and task-specific metrology inquiry contract","identifier":ID,"source_path":"release/hr-v0/lot-a-inquiry-p0.2/package-status.json","configuration_state":"CURRENT CONTROLLED DRAFT - NOTHING SENT OR AUTHORIZED","release_boundary":"five inquiry routes, 44 unique questions, 15 bid rows and all evidence/decisions open","warning":WARNING});write_csv(CFG/"current-configuration-map.csv",cf,current)
    supers,sf=read_csv(CFG/"supersession-map.csv");supers.extend([
      {"record_id":"SUP-28","prior_identifier":"HR-V0-LOT-A-SRC-P0.1","current_or_required_successor":ID,"disposition":"SUPERSEDED FOR CURRENT SUPPLIER-INQUIRY PLANNING; HISTORICAL PRICE/SOURCE SNAPSHOT RETAINED","use_authorized":"NO","warning":WARNING},
      {"record_id":"SUP-29","prior_identifier":"HR-V0-EVAL-ACQ-P0.1","current_or_required_successor":ID,"disposition":"SUPERSEDED FOR CURRENT METROLOGY-INQUIRY PLANNING; HISTORICAL PROVIDER RESEARCH RETAINED","use_authorized":"NO","warning":WARNING},
      {"record_id":"SUP-30","prior_identifier":"HR-V0-CONFIG-REC-P0.18","current_or_required_successor":"HR-V0-CONFIG-REC-P0.19","disposition":"SUPERSEDED BY R255 CONFIGURATION RECORD ONLY","use_authorized":"NO","warning":WARNING}]);write_csv(CFG/"supersession-map.csv",sf,supers)
    ch,hf=read_csv(CFG/"open-holds.csv")
    for i,g in enumerate(gates,1):ch.append({"hold_id":f"HOLD-{82+i:02d}","hold":f"{ID}: {g['decision']}","state":"OPEN","closure_evidence":g["evidence_required"],"warning":WARNING})
    write_csv(CFG/"open-holds.csv",hf,ch)
    ca,af=read_csv(CFG/"acceptance-matrix.csv")
    for i,a in enumerate(acceptance,1):ca.append({"acceptance_id":f"ACC-{115+i:03d}","criterion":f"{ID}: {a['criterion']}","execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":"","warning":WARNING})
    write_csv(CFG/"acceptance-matrix.csv",af,ca)
    gates_cfg,gf=read_csv(CFG/"gate-impact.csv")
    for r in gates_cfg:
      if r["gate_id"] in {"EG-002","EG-003","EG-005","EG-007"}:
        r["evidence_added"]+=f"; {ID} current unsent supplier/metrology inquiry and response-evaluation route"
        r["remaining_evidence"]+="; separately authorized transmissions; accepted written supplier identity/quote; received articles; accepted provider methods/calibration/uncertainty; executed physical evidence"
    write_csv(CFG/"gate-impact.csv",gf,gates_cfg)
    sh,hshf=read_csv(CFG/"source-hash-register.csv");sh.append({"source_path":"release/hr-v0/lot-a-inquiry-p0.2/package-status.json","sha256":sha(REL/"package-status.json"),"role":"Lot A supplier and metrology inquiry contract","warning":WARNING});write_csv(CFG/"source-hash-register.csv",hshf,sh)
    cs=json.loads((CFG/"package-status.json").read_text(encoding="utf-8"));cs.update({"identifier":"HR-V0-CONFIG-REC-P0.19","round":"R255","current_records":38,"supersession_records":30,"open_holds":97,"acceptance_rows":130});(CFG/"package-status.json").write_text(json.dumps(cs,indent=2)+"\n",encoding="utf-8")
    (CFG/"README.md").write_text(f"# HR-V0-CONFIG-REC-P0.19\n\n> **{WARNING}**\n\nR255 adds {ID} and supersedes two historical inquiry plans for current use. 97 holds and 130 unexecuted acceptances remain. Nothing is sent or authorized.\n",encoding="utf-8")
    (CFG/"index.html").write_text(guide(routes,trans,robotis,metro,bids,evidence,gates,workflow),encoding="utf-8");manifest(CFG);shutil.copytree(CFG,CFGR);manifest(CFGR)
    print(f"Generated {ID}: 5 routes; 44 unique questions; 0 sends/responses/authorizations; configuration P0.19")
if __name__=="__main__":main()
