#!/usr/bin/env python3
"""Generate R250 qualified-review-only datum/GD&T proposal and P0.14 config."""
from __future__ import annotations
import csv,hashlib,html,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];IDENT="HR-V0-GDT-REVIEW-P0.1";CFGID="HR-V0-CONFIG-REC-P0.14";WARNING="PRELIMINARY - NOT APPROVED FOR PROCUREMENT, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"
SRC=ROOT/"mechanical/drawings/hr-v0-gdt-review-p0.1";REL=ROOT/"release/hr-v0/gdt-review-p0.1";OLD=ROOT/"configuration/hr-v0-config-reconciliation-p0.13";CFG=ROOT/"configuration/hr-v0-config-reconciliation-p0.14";CFGR=ROOT/"release/hr-v0/configuration-reconciliation-p0.14"
def rd(p):
    with p.open(encoding="utf-8-sig",newline="") as h:r=csv.DictReader(h);return list(r),list(r.fieldnames or [])
def wr(p,f,rs):
    p.parent.mkdir(parents=True,exist_ok=True)
    with p.open("w",encoding="utf-8",newline="") as h:w=csv.DictWriter(h,fieldnames=f,lineterminator="\n");w.writeheader();w.writerows({k:r.get(k,"") for k in f} for r in rs)
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def man(d):
    rs=[]
    for p in sorted(x for x in d.rglob("*") if x.is_file() and x.name!="file-manifest.csv"):rs.append({"path":p.relative_to(d).as_posix(),"bytes":p.stat().st_size,"sha256":sh(p)})
    wr(d/"file-manifest.csv",["path","bytes","sha256"],rs)
def cm(rs):return [dict(r,warning=WARNING) for r in rs]
def page(title,intro,d,names):
    ss=[]
    for n in names:
        rs,fs=rd(d/n);head=''.join(f'<th>{html.escape(f.replace("_"," "))}</th>' for f in fs);body=''.join('<tr>'+''.join(f'<td>{html.escape(str(r[f]))}</td>' for f in fs)+'</tr>' for r in rs);ss.append(f"<section><h2>{n[:-4].replace('-',' ').title()}</h2><p><a href='{n}'>Download {n}</a></p><div class='table'><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div></section>")
    return f"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title}</title><style>:root{{--ink:#082a4a;--blue:#075ea8;--sky:#dff3ff;--gold:#f3bd28;--paper:#f8fbfd;--line:#9bc6e4;--danger:#8d1721}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:clamp(16px,1.2vw,18px)/1.55 system-ui,sans-serif}}header,main{{max-width:1500px;margin:auto;padding:clamp(18px,3vw,42px)}}header{{background:linear-gradient(135deg,var(--ink),var(--blue));color:white;max-width:none}}header>div{{max-width:1500px;margin:auto}}.warning{{font-size:clamp(16px,1.3vw,20px);font-weight:800;color:#fff2bd;border:3px solid var(--gold);padding:14px;border-radius:12px}}h1{{font-size:clamp(32px,5vw,62px);line-height:1.05}}h2{{font-size:clamp(24px,2.6vw,36px)}}.status{{font-size:18px;font-weight:800;color:var(--danger)}}a{{font-size:16px;font-weight:700;color:var(--blue)}}.table{{overflow:auto;background:white;border:2px solid var(--line);border-radius:12px}}table{{border-collapse:collapse;width:100%;min-width:1050px}}th,td{{padding:12px 14px;text-align:left;vertical-align:top;border-bottom:1px solid #cce1ef;font-size:14px;line-height:1.45}}th{{background:var(--sky)}}@media(max-width:600px){{header,main{{padding:18px}}h1{{font-size:34px}}}}</style></head><body><header><div><p class='warning'>{WARNING}</p><h1>{title}</h1><p>{intro}</p></div></header><main><p class='status'>PROPOSED FOR QUALIFIED REVIEW ONLY · FORMAL GD&T NOT RELEASED · DRAWING GEOMETRY UNCHANGED</p>{''.join(ss)}</main></body></html>"""
def package():
    for d in (SRC,REL):
        if d.exists():shutil.rmtree(d)
        d.mkdir(parents=True)
    parts=[("MV0-C01","four 32 x 16 M2.5 interface holes","two M5 end-tap holes"),("MV0-C04","four asymmetric H104 holes","two M5 end-tap holes"),("MV0-C05","four 32 x 16 S102 holes","two 60 mm-spaced column holes"),("MV0-C06","four 32 x 16 H101 holes","two M5 forearm holes and striker rails"),("MV0-C07","four 32 x 16 S102 holes","two M5 beam holes and catch rails")]
    dat=[];fcf=[];unc=[]
    for p,b,c in parts:
        dat.append({"part_id":p,"datum_A_candidate":"non-countersink broad mounting face","datum_B_candidate":b,"datum_C_candidate":c,"functional_intent":"A seats assembly; B locates/clock-controls primary mating pattern; C resolves remaining interface/stop relationship","standard_basis":"ASME Y14.5-2018 (R2024)","proposal_state":"PROPOSED - QUALIFIED DISPOSITION REQUIRED","fabrication_authorized":"FALSE","warning":WARNING})
        for cid,feature,proposal,basis in [("01","datum A flatness","0.15 mm","existing flatness limit retained"),("02","opposite broad face parallelism to A","0.10 mm | A","existing parallelism limit retained"),("03",b,"diametrical position 0.14 mm | A | B/C as applicable","0.14 mm is only a review proposal derived from prior +/-0.05 mm rectangular coordinate envelope; no equivalence/fit approval claimed"),("04",c,"diametrical position 0.14 mm | A | B/C as applicable","same review-only derivation; contact rails require separate profile/contact disposition")]:fcf.append({"control_id":f"{p}-FCF-{cid}","part_id":p,"feature":feature,"proposed_control":proposal,"derivation":basis,"material_condition":"RFS PROPOSED","standard_interpretation":"QUALIFIED REVIEW REQUIRED","released":"NO","warning":WARNING})
        for meas,tol in [("flatness","0.15 mm"),("parallelism","0.10 mm"),("hole true position proposal","0.14 mm diametrical")]:unc.append({"part_id":p,"measurand":meas,"tolerance":tol,"instrument_method":"CMM or qualified equivalent; method selection required","maximum_expanded_uncertainty":"SELECTION REQUIRED BEFORE FAI","coverage_factor":"SELECTION REQUIRED","calibration_traceability":"SELECTION REQUIRED","method_validation":"NOT EXECUTED","warning":WARNING})
    datasets={"datum-reference-frame-proposal.csv":(["part_id","datum_A_candidate","datum_B_candidate","datum_C_candidate","functional_intent","standard_basis","proposal_state","fabrication_authorized","warning"],dat),"feature-control-proposal.csv":(["control_id","part_id","feature","proposed_control","derivation","material_condition","standard_interpretation","released","warning"],fcf),"inspection-uncertainty-allocation.csv":(["part_id","measurand","tolerance","instrument_method","maximum_expanded_uncertainty","coverage_factor","calibration_traceability","method_validation","warning"],unc)}
    sources=[("ASME-Y14.5","ASME Y14.5-2018 (R2024)","https://www.asme.org/codes-standards/find-codes-standards/y14-5-dimensioning-tolerancing/2018","symbols/rules/definitions; licensed standard text not reproduced"),("ASME-Y14.43","ASME Y14.43-2011 (R2020)","https://www.asme.org/codes-standards/find-codes-standards/y14-43-dimensioning-tolerancing-principles-gages-fixtures","fixture/gage principles; Y14.5 itself is not a gaging standard"),("NIST-TN1297","NIST Technical Note 1297","https://www.nist.gov/pml/nist-technical-note-1297","measurement uncertainty evaluation/reporting"),("R247","current five-part held shop package","release/hr-v0/mechanical-shop-rfq-assembly-p0.1/package-status.json","geometry/title/RFQ source")]
    datasets["source-register.csv"]=(['source_id','source','url_or_path','use','verification_date','warning'],cm([{"source_id":a,"source":b,"url_or_path":c,"use":d,"verification_date":"2026-08-11"} for a,b,c,d in sources]))
    qs=["Accept or revise each functional datum feature and degree-of-freedom constraint.","Confirm whether pattern datums require MMB/MMC or remain RFS.","Confirm whether the proposed 0.14 mm diametrical position preserves intended fit relative to the prior rectangular coordinate zone.","Allocate datum precedence for the asymmetric H104 pattern.","Define profile controls for C06/C07 rails and contact surfaces.","Define countersink axis/coaxiality/profile controls and received-head functional acceptance.","Resolve thickness size, flatness and parallelism interaction.","Specify datum simulators, restraint, probing strategy, temperature and alignment.","Select per-measurand expanded uncertainty and decision rule.","Confirm first-article sampling and raw-data retention.","Confirm drawing/model authority and conflict precedence.","Sign a configuration-bound disposition or reject the proposal."]
    datasets["qualified-review-checklist.csv"]=(['review_id','question','response','evidence_uri','reviewer','state','warning'],cm([{"review_id":f"GDT-R-{i:02d}","question":q,"response":"","evidence_uri":"","reviewer":"","state":"NOT EXECUTED"} for i,q in enumerate(qs,1)]))
    holds=["Licensed/current standards available to qualified reviewer","Functional datum scheme accepted for all five parts","FCF values/modifiers and profile/contact controls accepted","Countersink and received-fastener functional controls accepted","Inspection fixture/probing/alignment method accepted","Uncertainty budgets and conformity decision rules accepted","Successor drawings updated and independently checked","Provider capability/DFM response accepted","First articles measured and raw reports accepted","Received mating-part dry fits accepted","Configuration-bound qualified signature recorded","Separate fabrication/assembly authority issued"]
    datasets["open-holds.csv"]=(['hold_id','hold','state','closure_evidence','release_effect','warning'],cm([{"hold_id":f"R250-H{i:02d}","hold":q,"state":"OPEN","closure_evidence":"NOT EXECUTED","release_effect":"BLOCKS FORMAL GD&T/FABRICATION RELEASE"} for i,q in enumerate(holds,1)]))
    acc=["All five functional datum reference frames accepted.","All twenty proposed feature controls accepted or revised.","C06/C07 contact profile and datum relationship accepted.","Countersink functional controls and received head gauge accepted.","CMM/inspection fixture and alignment method validated.","Measurement uncertainty and conformity decision rules accepted.","Successor drawings and exact STEP/DXF identities independently reconciled.","Provider DFM and inspection capability accepted.","Five first articles and received dry fits accepted.","Qualified release and separate work authority signed."]
    datasets["acceptance-matrix.csv"]=(['acceptance_id','criterion','execution_state','result','evidence_uri','approver','warning'],cm([{"acceptance_id":f"R250-ACC-{i:02d}","criterion":q,"execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":""} for i,q in enumerate(acc,1)]))
    for n,(f,rs) in datasets.items():wr(SRC/n,f,rs)
    status={"identifier":IDENT,"round":"R250","state":"QUALIFIED-REVIEW-ONLY GD&T PROPOSAL","parts":5,"datum_proposals":5,"feature_control_proposals":20,"uncertainty_rows":15,"review_questions":12,"open_holds":12,"acceptance_rows":10,"drawing_geometry_changed":False,"formal_gdt_released":False,"qualified_review_complete":False,"procurement_authorized":False,"fabrication_authorized":False,"assembly_authorized":False,"connection_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False,"warning":WARNING};(SRC/"package-status.json").write_text(json.dumps(status,indent=2)+"\n",encoding="utf-8",newline="\n");(SRC/"README.md").write_text(f"# {IDENT}\n\n> **{WARNING}**\n\nFive functional datum schemes and twenty feature-control candidates are proposed for qualified review. No drawing geometry changes, formal release, physical evidence or work authority exists.\n",encoding="utf-8",newline="\n")
    for p in SRC.iterdir():
        if p.is_file() and p.name!="file-manifest.csv":shutil.copy2(p,REL/p.name)
    (REL/"index.html").write_text(page("HR-V0 datum and GD&T qualified-review proposal","Five functional datum schemes, twenty review-only feature controls, inspection uncertainty allocation and a signed-disposition route.",REL,list(datasets)),encoding="utf-8",newline="\n");man(SRC);man(REL)
def config():
    for d in (CFG,CFGR):
        if d.exists():shutil.rmtree(d)
        shutil.copytree(OLD,d)
    cur,f=rd(CFG/"current-configuration-map.csv");cur.append({"record_id":"CFG-34","role":"five-part datum/GD&T qualified-review proposal","identifier":IDENT,"source_path":"release/hr-v0/gdt-review-p0.1/package-status.json","configuration_state":"CURRENT REVIEW PROPOSAL - FORMAL GD&T NOT RELEASED","release_boundary":"five datum and twenty feature-control proposals; qualified disposition, drawings, DFM, FAI and physical fit open","warning":WARNING});wr(CFG/"current-configuration-map.csv",f,cur)
    sup,f=rd(CFG/"supersession-map.csv");sup.append({"record_id":"SUP-21","prior_identifier":"HR-V0-CONFIG-REC-P0.13","current_or_required_successor":CFGID,"disposition":"SUPERSEDED BY R250 CONFIGURATION RECORD ONLY","use_authorized":"NO","warning":WARNING});wr(CFG/"supersession-map.csv",f,sup)
    hs,f=rd(CFG/"open-holds.csv");
    for i,q in enumerate(["Five-part datum/FCF qualified disposition","Inspection fixture/method/uncertainty acceptance","Successor controlled drawings","Provider DFM/FAI/received fit","Qualified release and separate work authority"],56):hs.append({"hold_id":f"HOLD-{i}","hold":q,"state":"NOT EXECUTED","closure_evidence":"Signed configuration-bound evidence","warning":WARNING})
    wr(CFG/"open-holds.csv",f,hs);ac,f=rd(CFG/"acceptance-matrix.csv")
    for i,q in enumerate(["R250 datum schemes accepted","R250 FCFs/modifiers accepted","R250 contact/countersink controls accepted","R250 inspection method accepted","R250 uncertainty/decision rules accepted","R250 successor drawings accepted","R250 DFM/FAI/fit accepted","R250 qualified release signed"],82):ac.append({"acceptance_id":f"ACC-{i:02d}","criterion":q,"execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":"","warning":WARNING})
    wr(CFG/"acceptance-matrix.csv",f,ac);st=json.loads((CFG/"package-status.json").read_text());st.update({"identifier":CFGID,"round":"R250","current_records":34,"supersession_records":21,"open_holds":60,"acceptance_rows":89,"gdt_review":IDENT});(CFG/"package-status.json").write_text(json.dumps(st,indent=2)+"\n");(CFG/"README.md").write_text(f"# {CFGID}\n\n> **{WARNING}**\n\nR250 adds a qualified-review-only GD&T proposal. Formal GD&T remains unreleased. Sixty holds and eighty-nine unexecuted acceptances remain.\n")
    hrs=[]
    for r in cur:p=ROOT/r["source_path"];hrs.append({"source_path":r["source_path"],"sha256":sh(p),"role":r["role"],"warning":WARNING})
    wr(CFG/"source-hash-register.csv",["source_path","sha256","role","warning"],hrs);man(CFG)
    for p in CFG.iterdir():
        if p.is_file() and p.name!="file-manifest.csv":shutil.copy2(p,CFGR/p.name)
    (CFGR/"index.html").write_text(page("HR-V0 configuration reconciliation P0.14","Current identifiers and holds after the R250 datum/GD&T review proposal.",CFGR,["current-configuration-map.csv","supersession-map.csv","gate-impact.csv","open-holds.csv","acceptance-matrix.csv"]));man(CFGR)
def main():package();config();print("Generated R250 GD&T review proposal and P0.14; formal release remains false")
if __name__=="__main__":main()
