#!/usr/bin/env python3
"""Generate R275 J2 soft-contact-pad candidate and dynamic load-case boundary."""
from __future__ import annotations

import csv
import hashlib
import html
import json
import math
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "mechanical/stops/hr-v0-j2-soft-contact-pad-p0.1"
REL = ROOT / "release/hr-v0/j2-soft-contact-pad-p0.1"
CFG0 = ROOT / "configuration/hr-v0-config-reconciliation-p0.38"
CFG = ROOT / "configuration/hr-v0-config-reconciliation-p0.39"
CFG_REL = ROOT / "release/hr-v0/configuration-reconciliation-p0.39"
IDENT = "HR-V0-J2-SOFT-CONTACT-PAD-P0.1"
CFG_IDENT = "HR-V0-CONFIG-REC-P0.39"
WARNING = "PRELIMINARY - NOT APPROVED FOR PROCUREMENT, QUOTATION, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"

def write_csv(path: Path, records: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w=csv.DictWriter(f, fieldnames=list(records[0]), lineterminator="\n"); w.writeheader(); w.writerows(records)
def rows(path: Path):
    with path.open(newline="", encoding="utf-8-sig") as f: return list(csv.DictReader(f))
def sha(path: Path): return hashlib.sha256(path.read_bytes()).hexdigest()
def manifest(directory: Path):
    write_csv(directory/"file-manifest.csv", [{"relative_path":p.relative_to(directory).as_posix(),"sha256":sha(p),"bytes":p.stat().st_size,"warning":WARNING} for p in sorted(directory.rglob("*")) if p.is_file() and p.name!="file-manifest.csv"])
def table(rs):
    fs=list(rs[0]); h="".join(f"<th>{html.escape(x.replace('_',' '))}</th>" for x in fs); b="".join("<tr>"+"".join(f"<td>{html.escape(str(r.get(x,'')))}</td>" for x in fs)+"</tr>" for r in rs); return f"<div class='scroll'><table><thead><tr>{h}</tr></thead><tbody>{b}</tbody></table></div>"

def main() -> int:
    if PKG.exists(): shutil.rmtree(PKG)
    PKG.mkdir(parents=True)
    sources=[
      {"source_id":"PAD-SRC-001","manufacturer":"Rogers Corporation","identity":"PORON 4790-92-25024-04P; product 2300327","document":"17-085 PORON 4790-92 extra soft slow rebound supported datasheet","revision_or_date":"1224-PDF / publication 17-085 (2024); checked 2026-08-12","official_url":"https://rogerscorp.com/-/media/project/rogerscorp/documents/elastomeric-material-solutions/poron/english/data-sheets/17-085-poron-4790-92-25024-p-extra-soft---slow-rebound---supported.pdf","verified":"0.61 +/-0.08 mm; 0.05 mm PET support; density 400 kg/m3 +/-10%; CFD 8..58 kPa at 25%; compression set maxima and temperature data","boundary":"not an energy/stall-stop rating; quasi-static test speed differs from robot contact","state":"PREFERRED TEST-COUPON CANDIDATE / UNSELECTED","warning":WARNING},
      {"source_id":"PAD-SRC-002","manufacturer":"Rogers Corporation","identity":"PORON availability brochure; product 2300327","document":"PORON polyurethane product availability brochure","revision_or_date":"current brochure; checked 2026-08-12","official_url":"https://www.rogerscorp.com/-/media/project/rogerscorp/documents/elastomeric-material-solutions/poron/english/product-availability/17-082-poron-polyurethanes-product-availability-brochure.pdf","verified":"2300327 listed as 0.61 mm supported roll product","boundary":"current quote, minimum order, lot and CoC remain open","state":"COMMERCIAL REFERENCE / QUOTE REQUIRED","warning":WARNING},
      {"source_id":"PAD-SRC-003","manufacturer":"Rogers Corporation","identity":"4790-92-30012-04P; product 2300392","document":"17-083 thinner supported alternative","revision_or_date":"1224-PDF / publication 17-083; checked 2026-08-12","official_url":"https://www.rogerscorp.com/-/media/project/rogerscorp/documents/elastomeric-material-solutions/poron/english/data-sheets/17-083-poron-4790-92-30012-p-extra-soft---slow-rebound---supported.pdf","verified":"0.30 +/-0.08 mm; density 480 kg/m3 +/-10%; CFD 16..94 kPa at 25%","boundary":"less travel; exact sheet lacks complete project life/application evidence","state":"SECONDARY TEST-COUPON CANDIDATE / UNSELECTED","warning":WARNING},
      {"source_id":"PAD-SRC-004","manufacturer":"ACE Controls","identity":"MC5M-3-B","document":"MC5M miniature shock absorber catalog and operating instructions","revision_or_date":"live manufacturer page and instructions 2023-12-20; checked 2026-08-12","official_url":"https://www.acecontrols.com/us/products/automation-control/miniature-shock-absorbers/mc5-to-mc75/mc5m/mc5m-1-b.html","verified":"6 in-lb per cycle; 4 mm stroke; M5x0.5; 1.89 ft/s minimum impact speed; axial mounting; <=2 degree side load","boundary":"4 mm stroke exceeds 0.75 mm envelope and minimum speed is about 59x HR-V0 10 deg/s tangent speed","state":"REJECTED FOR CURRENT GEOMETRY / MANUFACTURER APPLICATION REVIEW REQUIRED FOR REDESIGN","warning":WARNING},
    ]
    write_csv(PKG/"source-register.csv",sources)
    candidate=[{"candidate_id":"PAD-CAND-001","manufacturer":"Rogers Corporation","product_number":"2300327","material":"PORON 4790-92-25024-04P extra soft slow rebound supported","finished_coupon_nominal_mm":"42 x 12 x 0.61","thickness_tolerance_mm":"0.61 +/-0.08; worst published 0.69 <= 0.75 envelope","retention":"SELECTION REQUIRED; shallow captive pocket preferred; no adhesive is supplied","functional_role":"sacrificial soft-contact/noise/rebound pad only; metal rails remain structural backup","selection_state":"UNSELECTED TEST-COUPON CANDIDATE","procurement_authorized":"NO","safety_credit":"NONE","warning":WARNING}]
    write_csv(PKG/"candidate-definition.csv",candidate)
    I=0.010144; w10=math.radians(10); w30=math.radians(30); e10=.5*I*w10*w10; e30=.5*I*w30*w30; work=189.721*0.00075
    load_cases=[
      {"case_id":"PAD-LC-001","case":"10 deg/s kinetic approach","formula":"0.5*I_eff*omega^2","inputs":"I_eff=0.010144 kg m2 excludes reflected rotor; omega=10 deg/s","result":f"{e10:.9f} J","disposition":"ARITHMETIC ONLY; INERTIA UNACCEPTED","required_successor":"accepted as-built inertia incl reflected rotor and maximum measured speed","warning":WARNING},
      {"case_id":"PAD-LC-002","case":"30 deg/s kinetic sensitivity","formula":"0.5*I_eff*omega^2","inputs":"same unaccepted I_eff; omega=30 deg/s","result":f"{e30:.9f} J","disposition":"SENSITIVITY ONLY; 30 DEG/S NOT RELEASED","required_successor":"fault/overspeed allocation and physical verification","warning":WARNING},
      {"case_id":"PAD-LC-003","case":"motor work through full 0.75 mm pad envelope","formula":"F_endpoint*stroke","inputs":"189.721 N from 10.6 N m / 55.871659 mm superseded radius-basis force; 0.00075 m","result":f"{work:.9f} J; {work/e10:.1f} x 10 deg/s kinetic energy","disposition":"ORDER-OF-MAGNITUDE WARNING ONLY","required_successor":"measured current/torque decay and exact contact-normal work integration","warning":WARNING},
      {"case_id":"PAD-LC-004","case":"single-rail full coupon pressure at endpoint screen","formula":"189.721 N / (42*12 mm2)","inputs":"full 504 mm2 area; no edge concentration","result":f"{189.721/504:.6f} MPa","disposition":"EXCEEDS PUBLISHED 25% CFD RANGE; PAD CANNOT CARRY STALL LOAD","required_successor":"dynamic force-stroke/bottom-out test at actual rate, temperature and tolerance","warning":WARNING},
      {"case_id":"PAD-LC-005","case":"twin-rail equal-share pressure","formula":"94.8605 N / (42*12 mm2)","inputs":"ideal equal share only","result":f"{94.8605/504:.6f} MPa","disposition":"NOT FAIL-SAFE; STILL ABOVE PUBLISHED 25% CFD RANGE","required_successor":"worst-tolerance first-contact and single-rail physical tests","warning":WARNING},
      {"case_id":"PAD-LC-006","case":"industrial shock absorber comparison","formula":"catalog geometry and velocity boundary","inputs":"ACE MC5M-3-B 4 mm stroke; >=0.576 m/s vs HR-V0 about 0.009751 m/s","result":"DOES NOT FIT / OUTSIDE CATALOG SPEED RANGE","disposition":"REJECT FOR P0.12 ENVELOPE","required_successor":"architecture change plus written ACE sizing if structural absorber is required","warning":WARNING},
    ]
    write_csv(PKG/"dynamic-load-case-register.csv",load_cases)
    tests=[]
    for i,case in enumerate(["incoming identity/CoC and thickness <=0.75 mm","die-cut geometry flatness and captive retention","force-deflection and hysteresis at actual ~9.75 mm/s and min/max temperature","single-rail 10 deg/s instrumented impact","twin-rail 10 deg/s instrumented impact and first-contact mismatch","current/torque/power-removal transient during contact","rebound and overtravel","compression set wear and retention through qualified cycle count","aging contamination and temperature exposure","correlation to accepted inertia/contact/load model"],1):
      tests.append({"test_id":f"PAD-TEST-{i:02d}","test":case,"configuration":"received 2300327 coupon and P0.12 metal backup; exact fixture/repetitions SELECTION REQUIRED","acceptance":"SELECTION REQUIRED by qualified mechanical/test review","execution":"NOT EXECUTED","result":"OPEN","evidence_uri":"","warning":WARNING})
    write_csv(PKG/"verification-matrix.csv",tests)
    holds_text=["Current supplier quote, exact 2300327 identity, lot and CoC accepted","Incoming thickness, coupon geometry and captive retention pass inspection","Exact contact point/normal and work path through tolerance are accepted","As-built inertia including reflected rotor is measured and accepted","Maximum approach/fault speed and current/torque decay are measured","Dynamic force-stroke, hysteresis, bottom-out and rebound are characterized","Temperature, aging, contamination, compression-set and life limits are qualified","Single-rail and twin-rail tests correlate with accepted nonlinear model","Metal backup C06/C07 and full joined load path are accepted independently","Guard/overtravel/pinch envelope includes pad tolerance and failure","Qualified release confirms pad has zero sole structural-stop and safety credit","Separate procurement, assembly and powered-work authorities are signed"]
    holds=[{"hold_id":f"R275-H{i:02d}","hold":x,"state":"OPEN","execution":"NOT EXECUTED","release_effect":"BLOCKS PAD SELECTION AND MOTION","warning":WARNING} for i,x in enumerate(holds_text,1)]
    write_csv(PKG/"open-holds.csv",holds)
    write_csv(PKG/"acceptance-matrix.csv",[{"acceptance_id":f"R275-ACC-{i:02d}","criterion":x,"execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":"","warning":WARNING} for i,x in enumerate(holds_text,1)])
    status={"identifier":IDENT,"round":"R275","date":"2026-08-12","candidate":"Rogers 2300327","functional_role":"soft-contact/noise/rebound pad ahead of structural metal backup","candidate_selected":False,"sole_structural_stop":False,"procurement_authorized":False,"assembly_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False,"open_holds":12,"warning":WARNING}
    (PKG/"package-status.json").write_text(json.dumps(status,indent=2)+"\n",encoding="utf-8")
    (PKG/"README.md").write_text(f"# {IDENT}\n\n> **{WARNING}**\n\nR275 defines Rogers 2300327 only as an unselected sacrificial soft-contact pad ahead of the structural metal backup. It is not an energy-rated stop and carries no safety credit.\n",encoding="utf-8")
    page=f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>R275 J2 soft contact</title><style>:root{{--sky:#dff3ff;--blue:#082e55;--gold:#f3bd28;--paper:#f7fbff;--ink:#102338;--line:#79abd0;--hold:#fff0b8}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:clamp(16px,1.2vw,18px)/1.55 system-ui,sans-serif}}header,main{{padding:clamp(20px,4vw,52px)}}header{{background:linear-gradient(135deg,var(--blue),#0879be);color:white}}header>div,main{{max-width:1500px;margin:auto}}.warning{{border:3px solid var(--gold);padding:15px;border-radius:12px;font-size:clamp(16px,1.4vw,21px);font-weight:850;color:#fff1b5}}h1{{font-size:clamp(36px,5.5vw,70px);line-height:1.03}}h2{{font-size:clamp(25px,3vw,40px)}}.metrics{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:15px}}.metric,.card{{background:white;border:2px solid var(--line);border-radius:14px;padding:19px}}.metric strong{{display:block;color:#075e9c;font-size:31px}}.hold{{background:var(--hold);border:3px solid var(--gold);border-radius:14px;padding:20px}}section{{margin:34px 0}}.scroll{{overflow:auto;border:2px solid var(--line);border-radius:12px;background:white}}table{{border-collapse:collapse;width:100%;min-width:1120px}}th,td{{padding:12px 14px;text-align:left;vertical-align:top;border-bottom:1px solid #c6deed;font-size:14px;line-height:1.45}}th{{background:var(--sky)}}@media(max-width:600px){{header,main{{padding:18px}}}}</style></head><body><header><div><p class='warning'>{WARNING}</p><p>R275 &middot; {IDENT}</p><h1>The pad can soften contact. It cannot be the stop.</h1><p>Rogers 2300327 fits the 0.75 mm envelope on paper. Published compression data show that the metal rails must still carry structural load.</p></div></header><main><section class='metrics'><div class='metric'><strong>0.69 mm</strong>worst published thickness</div><div class='metric'><strong>{e10:.6f} J</strong>10 deg/s kinetic screen</div><div class='metric'><strong>{work:.3f} J</strong>motor-work warning</div><div class='metric'><strong>{work/e10:.0f}x</strong>motor work / kinetic</div><div class='metric'><strong>12</strong>open holds</div><div class='metric'><strong>0</strong>safety credit</div></section><section class='hold'><h2>The architecture decision</h2><p>The soft material is a sacrificial contact/noise/rebound layer. A defined metal-to-metal backup remains mandatory. If the bumper must absorb stall or fault energy by itself, the 0.75 mm architecture must change and a manufacturer must size the absorber.</p></section><section><h2>Load cases, not one magic factor</h2>{table(load_cases)}</section><section><h2>Primary-source boundary</h2>{table(sources)}</section><section><h2>Evidence still required</h2>{table(holds)}</section></main></body></html>"""
    (PKG/"index.html").write_text(page,encoding="utf-8"); manifest(PKG)
    if REL.exists(): shutil.rmtree(REL)
    shutil.copytree(PKG,REL); manifest(REL)

    for d in (CFG,CFG_REL):
      if d.exists(): shutil.rmtree(d)
    shutil.copytree(CFG0,CFG)
    current=rows(CFG/"current-configuration-map.csv"); current.append({"record_id":"CFG-58","role":"unselected J2 soft-contact pad and dynamic evidence contract","identifier":IDENT,"source_path":"release/hr-v0/j2-soft-contact-pad-p0.1/package-status.json","configuration_state":"CURRENT REVIEW EVIDENCE - TEST COUPON UNSELECTED","release_boundary":"pad has no structural-stop/safety credit; dynamic/physical/qualified closure open","warning":WARNING}); write_csv(CFG/"current-configuration-map.csv",current)
    supers=rows(CFG/"supersession-map.csv"); supers.append({"record_id":"SUP-53","prior_identifier":"HR-V0-CONFIG-REC-P0.38","current_or_required_successor":CFG_IDENT,"disposition":"superseded for package indexing only; mechanical P0.8 remains current unaccepted and P0.12/A04/pad remain unselected","use_authorized":"NO","warning":WARNING}); write_csv(CFG/"supersession-map.csv",supers)
    ch=rows(CFG/"open-holds.csv"); ca=rows(CFG/"acceptance-matrix.csv")
    for h in holds: ch.append({"hold_id":f"HOLD-{len(ch)+1:03d}","hold":f"{IDENT}: {h['hold']}","state":"NOT EXECUTED","closure_evidence":"controlled physical result and qualified acceptance","warning":WARNING})
    for h in holds: ca.append({"acceptance_id":f"ACC-{len(ca)+1:03d}","criterion":f"{IDENT}: {h['hold']}","execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":"","warning":WARNING})
    write_csv(CFG/"open-holds.csv",ch); write_csv(CFG/"acceptance-matrix.csv",ca)
    st=json.loads((CFG/"package-status.json").read_text(encoding="utf-8")); st.update({"identifier":CFG_IDENT,"round":"R275","current_records":len(current),"supersession_records":len(supers),"open_holds":len(ch),"acceptance_rows":len(ca),"j2_soft_contact_review":IDENT,"j2_pad_selected":False,"procurement_authorized":False,"assembly_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False}); (CFG/"package-status.json").write_text(json.dumps(st,indent=2)+"\n",encoding="utf-8")
    (CFG/"README.md").write_text(f"# {CFG_IDENT}\n\n> **{WARNING}**\n\nR275 indexes an unselected Rogers 2300327 soft-contact test-coupon candidate. It has no sole structural-stop or safety credit.\n",encoding="utf-8")
    write_csv(CFG/"source-hash-register.csv",[{"source_path":r["source_path"],"sha256":sha(ROOT/r["source_path"]),"role":r["role"],"warning":WARNING} for r in current]); shutil.copy2(PKG/"index.html",CFG/"index.html"); manifest(CFG); shutil.copytree(CFG,CFG_REL); manifest(CFG_REL)
    (ROOT/"docs/hr-v0-j2-soft-contact-pad-p0.1.md").write_text(f"# HR-V0 J2 soft-contact pad P0.1\n\n> **{WARNING}**\n\nR275 names Rogers `2300327` / PORON `4790-92-25024-04P` as the preferred unselected test coupon. Its published 0.61 +/-0.08 mm thickness fits the current 0.75 mm envelope, but its compression data are not an energy- or stall-stop rating.\n\nThe current unaccepted inertia gives {e10:.9f} J at 10 deg/s. By contrast, the radius-basis endpoint force doing work through 0.75 mm gives {work:.9f} J, about {work/e10:.1f} times the kinetic energy. That comparison is deliberately an order-of-magnitude warning: exact contact-normal work and measured torque decay remain open. It proves why the metal backup must remain structural and why power-removal time dominates.\n\nACE `MC5M-3-B`, the smallest catalogued energy-rated comparator found, needs 4 mm stroke and a minimum listed impact speed about 59 times HR-V0's nominal 10 deg/s tangent speed; it is rejected for the current envelope.\n\n[Interactive pad guide](../release/hr-v0/j2-soft-contact-pad-p0.1/index.html)\n",encoding="utf-8")
    (ROOT/"docs/reviews/2026-08-12-r275-independent-review-request.md").write_text(f"# R275 independent review request\n\n> **{WARNING}**\n\nPlease review `{IDENT}` for manufacturer-source accuracy, geometry compatibility, pressure/energy arithmetic, explicit separation of quasistatic drive work from kinetic impact, metal-backup requirement, test completeness and fail-closed authority. No product is selected and no motion or energization is authorized.\n",encoding="utf-8")
    rd=ROOT/"README.md"; tx=rd.read_text(encoding="utf-8"); mk="## Start here\n\n"; links="- [R275 J2 soft-contact pad candidate](docs/hr-v0-j2-soft-contact-pad-p0.1.md)\n- [R275 independent review request](docs/reviews/2026-08-12-r275-independent-review-request.md)\n- [R275 validation record](docs/reviews/2026-08-12-r275-validation-record.md)\n- [Interactive R275 pad guide](release/hr-v0/j2-soft-contact-pad-p0.1/index.html)\n- [Interactive configuration reconciliation P0.39](release/hr-v0/configuration-reconciliation-p0.39/index.html)\n"; tx=tx if links.splitlines()[0] in tx else tx.replace(mk,mk+links); tx=tx.replace("Two hundred seventy-four rounds are complete: R01-R274.","Two hundred seventy-five rounds are complete: R01-R275."); rd.write_text(tx,encoding="utf-8")
    hd=ROOT/"docs/handoff-current.md"; old=hd.read_text(encoding="utf-8"); block=f"R275 J2 soft-contact pad boundary: **`{IDENT}` names Rogers 2300327 only as an unselected sacrificial contact/noise/rebound pad ahead of the metal backup. Motor-work uncertainty dominates nominal kinetic energy; twelve physical/qualified holds and zero work authority remain.**\n\n"; hd.write_text(old if old.startswith("R275 J2 soft-contact pad boundary:") else block+old,encoding="utf-8")
    lg=ROOT/"docs/review-ledger.md"; tx=lg.read_text(encoding="utf-8").replace("Two hundred seventy-four rounds are complete (R01-R274).","Two hundred seventy-five rounds are complete (R01-R275).");
    if "| R275 |" not in tx: tx=tx.rstrip()+"\n| R275 | 2026-08-12 | J2 soft-contact pad and dynamic load-case boundary | Codex project-owned research/mechanical correction informed by independent manufacturer-source research; not independent or qualified review | The 0.75 mm bumper envelope had no viable named material and the stop discussion risked conflating tiny kinetic energy with sustained motor work. | Named Rogers 2300327 as an unselected sacrificial pad, rejected ACE MC5M-3-B for current geometry/speed, separated kinetic/drive-work/pressure cases and added ten blank tests plus twelve holds. Metal backup remains structural; zero safety/work authority. | `docs/hr-v0-j2-soft-contact-pad-p0.1.md`; `release/hr-v0/j2-soft-contact-pad-p0.1/`; `configuration/hr-v0-config-reconciliation-p0.39/` |\n"
    lg.write_text(tx,encoding="utf-8")
    print("Generated R275 J2 soft-contact pad package; no authority released")
    return 0
if __name__=="__main__": raise SystemExit(main())
