#!/usr/bin/env python3
"""Generate R251 minimum physical acquisition and unpowered metrology session."""
from __future__ import annotations
import csv,hashlib,html,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];ID="HR-V0-FIRST-SHOP-SESSION-P0.1";CID="HR-V0-CONFIG-REC-P0.15";W="PRELIMINARY - NOT APPROVED FOR PROCUREMENT, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"
SRC=ROOT/"mechanical/metrology/hr-v0-first-shop-session-p0.1";REL=ROOT/"release/hr-v0/first-shop-session-p0.1";OLD=ROOT/"configuration/hr-v0-config-reconciliation-p0.14";CFG=ROOT/"configuration/hr-v0-config-reconciliation-p0.15";CFGR=ROOT/"release/hr-v0/configuration-reconciliation-p0.15"
def rd(p):
    with p.open(encoding="utf-8-sig",newline="") as h:r=csv.DictReader(h);return list(r),list(r.fieldnames or [])
def wr(p,f,rs):
    p.parent.mkdir(parents=True,exist_ok=True)
    with p.open("w",encoding="utf-8",newline="") as h:w=csv.DictWriter(h,fieldnames=f,lineterminator="\n");w.writeheader();w.writerows({k:r.get(k,"") for k in f} for r in rs)
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def cm(rs):return [dict(r,warning=W) for r in rs]
def man(d):
    rs=[]
    for p in sorted(x for x in d.rglob("*") if x.is_file() and x.name!="file-manifest.csv"):rs.append({"path":p.relative_to(d).as_posix(),"bytes":p.stat().st_size,"sha256":sh(p)})
    wr(d/"file-manifest.csv",["path","bytes","sha256"],rs)
def page(title,intro,d,names):
    sec=[]
    for n in names:
        rs,fs=rd(d/n);hd=''.join(f'<th>{html.escape(x.replace("_"," "))}</th>' for x in fs);bd=''.join('<tr>'+''.join(f'<td>{html.escape(str(r[x]))}</td>' for x in fs)+'</tr>' for r in rs);sec.append(f"<section><h2>{n[:-4].replace('-',' ').title()}</h2><p><a href='{n}'>Download {n}</a></p><div class='table'><table><thead><tr>{hd}</tr></thead><tbody>{bd}</tbody></table></div></section>")
    return f"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title}</title><style>:root{{--ink:#082a4a;--blue:#075ea8;--sky:#dff3ff;--gold:#f3bd28;--paper:#f8fbfd;--line:#9bc6e4;--danger:#8d1721}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:clamp(16px,1.2vw,18px)/1.55 system-ui,sans-serif}}header,main{{max-width:1500px;margin:auto;padding:clamp(18px,3vw,42px)}}header{{background:linear-gradient(135deg,var(--ink),var(--blue));color:white;max-width:none}}header>div{{max-width:1500px;margin:auto}}.warning{{font-size:clamp(16px,1.3vw,20px);font-weight:800;color:#fff2bd;border:3px solid var(--gold);padding:14px;border-radius:12px}}h1{{font-size:clamp(32px,5vw,62px);line-height:1.05}}h2{{font-size:clamp(24px,2.6vw,36px)}}.status{{font-size:18px;font-weight:800;color:var(--danger)}}a{{font-size:16px;font-weight:700;color:var(--blue)}}.table{{overflow:auto;background:white;border:2px solid var(--line);border-radius:12px}}table{{border-collapse:collapse;width:100%;min-width:1050px}}th,td{{padding:12px 14px;text-align:left;vertical-align:top;border-bottom:1px solid #cce1ef;font-size:14px;line-height:1.45}}th{{background:var(--sky)}}@media(max-width:600px){{header,main{{padding:18px}}h1{{font-size:34px}}}}</style></head><body><header><div><p class='warning'>{W}</p><h1>{title}</h1><p>{intro}</p></div></header><main><p class='status'>PURCHASE BLOCKED &middot; SESSION NOT AUTHORIZED &middot; NO ASSEMBLY OR POWER &middot; ALL RESULTS BLANK</p>{''.join(sec)}</main></body></html>"""
def package():
    for d in (SRC,REL):
        if d.exists():shutil.rmtree(d)
        d.mkdir(parents=True)
    lot=ROOT/"release/hr-v0/lot-a-source-reconciliation-p0.1";jsm=ROOT/"test-fixtures/hr-v0/joint-stack-metrology-p0.1"
    datasets={}
    sources=[("SRC-01","Lot A source reconciliation",lot/"package-status.json"),("SRC-02","Lot A decision gates",lot/"decision-gate.csv"),("SRC-03","Joint-stack metrology status",jsm/"package-status.json"),("SRC-04","Joint-stack operations",jsm/"operation-sequence.csv"),("SRC-05","HSI trace",jsm/"hsi-trace.csv"),("SRC-06","R248 moving properties",ROOT/"release/hr-v0/moving-properties-closure-p0.1/package-status.json"),("SRC-07","R250 GD&T proposal",ROOT/"release/hr-v0/gdt-review-p0.1/package-status.json")]
    datasets["source-binding.csv"]=(['source_id','source','path','sha256','state','warning'],cm([{"source_id":a,"source":b,"path":p.relative_to(ROOT).as_posix(),"sha256":sh(p),"state":"BOUND INPUT - DOES NOT AUTHORIZE WORK"} for a,b,p in sources]))
    items,_=rd(lot/"item-register.csv");datasets["six-article-register.csv"]=(['article_id','joint','requested_identity','order_code','quantity','source_item','purchase_state','received_state','substitution_rule','warning'],cm([{"article_id":f"FSS-ART-{i:02d}","joint":j,"requested_identity":ident,"order_code":code,"quantity":"1","source_item":src,"purchase_state":"NOT AUTHORIZED","received_state":"NOT RECEIVED","substitution_rule":"NO SUBSTITUTION"} for i,(j,ident,code,src) in enumerate([("J1",items[0]["requested_identity"],items[0]["order_code"],"LOT-A-001"),("J2",items[0]["requested_identity"],items[0]["order_code"],"LOT-A-001"),("J1",items[1]["requested_identity"],items[1]["order_code"],"LOT-A-002"),("J2",items[1]["requested_identity"],items[1]["order_code"],"LOT-A-002"),("J1",items[2]["requested_identity"],items[2]["order_code"],"LOT-A-003"),("J2",items[2]["requested_identity"],items[2]["order_code"],"LOT-A-003")],1)]))
    gates,_=rd(lot/"decision-gate.csv");datasets["purchase-gate-snapshot.csv"]=(['gate_id','decision','evidence_required','source_state','current_state','authority','warning'],cm([{"gate_id":r["gate_id"],"decision":r["decision"],"evidence_required":r["evidence_required"],"source_state":r["state"],"current_state":"OPEN","authority":"NONE"} for r in gates]))
    qs,_=rd(lot/"supplier-question-register.csv");datasets["supplier-question-snapshot.csv"]=(['question_id','recipient','question','required_response','transmission_state','response','warning'],cm([{"question_id":r["question_id"],"recipient":r["recipient"],"question":r["question"],"required_response":r["required_response"],"transmission_state":"UNSENT","response":""} for r in qs]))
    ops,_=rd(jsm/"operation-sequence.csv");datasets["session-traveler.csv"]=(['operation_id','phase','action','inputs','output','hsi','stop_condition','source_state','session_state','authorization_record','evidence_uri','warning'],cm([{"operation_id":r["operation_id"],"phase":r["phase"],"action":r["action"],"inputs":r["inputs"],"output":r["output"],"hsi":r["hsi"],"stop_condition":r["stop_condition"],"source_state":r["state"],"session_state":"NOT EXECUTED","authorization_record":"","evidence_uri":""} for r in ops]))
    hp,_=rd(jsm/"hold-point-register.csv");datasets["hold-point-snapshot.csv"]=(['hold_id','before_operation','condition','required_signoff','failure_action','source_state','session_state','signer','evidence_uri','warning'],cm([{"hold_id":r["hold_id"],"before_operation":r["before_operation"],"condition":r["condition"],"required_signoff":r["required_signoff"],"failure_action":r["failure_action"],"source_state":r["state"],"session_state":"OPEN","signer":"","evidence_uri":""} for r in hp]))
    inst,_=rd(jsm/"instrument-capability-register.csv");datasets["instrument-readiness.csv"]=(['instrument_id','measurement','candidate_method','provisional_screening_capability','final_acceptance','evidence_required','source_status','session_status','selected_identity','calibration_uri','uncertainty_uri','warning'],cm([{"instrument_id":r["instrument_id"],"measurement":r["measurement"],"candidate_method":r["candidate_method"],"provisional_screening_capability":r["provisional_screening_capability"],"final_acceptance":r["final_acceptance"],"evidence_required":r["evidence_required"],"source_status":r["status"],"session_status":"NOT READY","selected_identity":"","calibration_uri":"","uncertainty_uri":""} for r in inst]))
    hsi,_=rd(jsm/"hsi-trace.csv");datasets["hsi-execution-register.csv"]=(['hsi','r84_route','operation','closure_possible_in_r84','remaining_dependency','source_state','session_result','accepted_value','uncertainty','evidence_uri','approver','warning'],cm([{"hsi":r["hsi"],"r84_route":r["r84_route"],"operation":r["operation"],"closure_possible_in_r84":r["closure_possible_in_r84"],"remaining_dependency":r["remaining_dependency"],"source_state":r["state"],"session_result":"NOT EXECUTED","accepted_value":"","uncertainty":"","evidence_uri":"","approver":""} for r in hsi]))
    roles=[("ROLE-01","program owner","purchase scope/max spend/ship-to authorization"),("ROLE-02","receiving inspector","receipt/quarantine/identity/contents"),("ROLE-03","qualified mechanical reviewer","fixture, temporary stack, results"),("ROLE-04","qualified metrology reviewer","instruments/method/uncertainty"),("ROLE-05","test conductor","traveler and stop-work control"),("ROLE-06","independent witness","zero-energy and evidence completeness"),("ROLE-07","configuration owner","article/hash/configuration freeze")]
    datasets["role-assignment-template.csv"]=(['role_id','role','responsibility','person','qualification_evidence_uri','acceptance','warning'],cm([{"role_id":a,"role":b,"responsibility":c,"person":"SELECTION REQUIRED","qualification_evidence_uri":"","acceptance":"OPEN"} for a,b,c in roles]))
    dirs=[("EVID-01","authorization","signed purchase/session scope"),("EVID-02","supplier","written answers and dated quote"),("EVID-03","receiving","labels/serials/lots/contents/photos"),("EVID-04","instruments","calibration/method/uncertainty"),("EVID-05","loose-metrology","raw CMM/dimensions/mass"),("EVID-06","temporary-stack","signed instruction/photos/config hash"),("EVID-07","axial-angle-envelope","raw data/point clouds/residuals"),("EVID-08","teardown","post-inspection/nonconformance/quarantine"),("EVID-09","disposition","signed HSI/result acceptance")]
    datasets["evidence-location-plan.csv"]=(['evidence_id','directory','required_content','exists','content_hash','state','warning'],cm([{"evidence_id":a,"directory":f"evidence/hr-v0/first-shop-session/{a.lower()}/","required_content":c,"exists":"FALSE","content_hash":"","state":"NOT CREATED / NOT EXECUTED"} for a,_,c in dirs]))
    stops=["SKU/model/communication contradiction unresolved","seller, stock, landed cost, maximum spend, ship-to or receiver not accepted","received marking/content/damage discrepancy","instrument calibration, capability, method or uncertainty not accepted","fixture loads case, connector, cable aperture or stop surface","temporary screw/depth/spacer/torque/reuse instruction absent","any source-capable equipment or powered connection in area","unexpected resistance, bottoming, gap, distortion, slip or contact","any attempt to infer cable/guard/load/bumper/supplier evidence","raw evidence, hash or required signature incomplete"]
    datasets["stop-work-register.csv"]=(['stop_id','condition','required_action','restart_authority','state','warning'],cm([{"stop_id":f"FSS-STOP-{i:02d}","condition":q,"required_action":"STOP, QUARANTINE/SEGREGATE, RECORD NONCONFORMANCE","restart_authority":"SELECTION REQUIRED QUALIFIED ROLE","state":"ACTIVE"} for i,q in enumerate(stops,1)]))
    holds=["ROBOTIS written -T/SKU binding","Complete dated six-article allocation and landed cost","Program-owner maximum spend/ship-to/receiving authorization","All articles received and quarantined without discrepancy","Roles and qualifications accepted","Instrument/method/uncertainty readiness accepted","Non-damaging fixture and temporary stack instruction accepted","Zero-energy area independently witnessed","Evidence locations and immutable configuration prepared","Separate unpowered session authorization issued","All HSI raw evidence completed and dispositioned","Teardown, post-inspection and quarantine completed"]
    datasets["open-holds.csv"]=(['hold_id','hold','state','closure_evidence','work_effect','warning'],cm([{"hold_id":f"R251-H{i:02d}","hold":q,"state":"OPEN","closure_evidence":"NOT EXECUTED","work_effect":"BLOCKS PURCHASE OR FIRST-SHOP SESSION AS APPLICABLE"} for i,q in enumerate(holds,1)]))
    acc=["All ten Lot A purchase gates accepted.","All eight supplier questions answered and accepted.","Six exact articles received, identified and quarantined.","Seven roles and qualifications accepted.","Six instruments/methods/uncertainties accepted.","Eight hold points signed before dependent operations.","Eighteen operations completed without stop-work event or unresolved NCR.","HSI-001..014 results and HSI-015..020 dependency states accepted.","All evidence hashes reproduce and teardown/quarantine passes.","Qualified disposition accepts results without granting build or powered-work authority."]
    datasets["acceptance-matrix.csv"]=(['acceptance_id','criterion','execution_state','result','evidence_uri','approver','warning'],cm([{"acceptance_id":f"R251-ACC-{i:02d}","criterion":q,"execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":""} for i,q in enumerate(acc,1)]))
    for n,(f,rs) in datasets.items():wr(SRC/n,f,rs)
    st={"identifier":ID,"round":"R251","state":"MINIMUM PHYSICAL ACQUISITION/UNPOWERED SESSION CONTRACT","articles":6,"purchase_gates":10,"supplier_questions":8,"operations":18,"hold_points":8,"instruments":6,"hsi_rows":20,"roles":7,"evidence_locations":9,"stop_conditions":10,"open_holds":12,"acceptance_rows":10,"supplier_contacted":False,"purchase_authorized":False,"session_authorized":False,"articles_received":0,"operations_executed":0,"hsi_accepted":0,"assembly_authorized":False,"connection_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False,"warning":W};(SRC/"package-status.json").write_text(json.dumps(st,indent=2)+"\n",encoding="utf-8");(SRC/"README.md").write_text(f"# {ID}\n\n> **{W}**\n\nOne controlled path from the blocked Lot A inquiry through receipt, quarantine and unpowered joint-stack metrology. All gates, questions, roles, evidence and results remain open.\n",encoding="utf-8")
    for p in SRC.iterdir():
        if p.is_file() and p.name!="file-manifest.csv":shutil.copy2(p,REL/p.name)
    (REL/"index.html").write_text(page("HR-V0 first physical shop session","A single fail-closed packet for the exact six-article acquisition, receipt, quarantine and unpowered joint-stack metrology needed before missing hard stops can be designed.",REL,list(datasets)),encoding="utf-8");man(SRC);man(REL)
def config():
    for d in (CFG,CFGR):
        if d.exists():shutil.rmtree(d)
        shutil.copytree(OLD,d)
    cur,f=rd(CFG/"current-configuration-map.csv");cur.append({"record_id":"CFG-35","role":"minimum physical acquisition and first unpowered shop-session contract","identifier":ID,"source_path":"release/hr-v0/first-shop-session-p0.1/package-status.json","configuration_state":"CURRENT FAIL-CLOSED SESSION CONTRACT - NOTHING AUTHORIZED","release_boundary":"purchase gates, supplier questions, receipt, roles, instruments, operations and HSI evidence all open","warning":W});wr(CFG/"current-configuration-map.csv",f,cur)
    sup,f=rd(CFG/"supersession-map.csv");sup.append({"record_id":"SUP-22","prior_identifier":"HR-V0-CONFIG-REC-P0.14","current_or_required_successor":CID,"disposition":"SUPERSEDED BY R251 CONFIGURATION RECORD ONLY","use_authorized":"NO","warning":W});wr(CFG/"supersession-map.csv",f,sup)
    hs,f=rd(CFG/"open-holds.csv");
    for i,q in enumerate(["Lot A supplier clarification and purchase gates","Six-article receipt/quarantine","Shop roles/instruments/fixture authorization","Unpowered 18-operation session","HSI evidence/disposition/teardown"],61):hs.append({"hold_id":f"HOLD-{i}","hold":q,"state":"NOT EXECUTED","closure_evidence":"Signed configuration-bound evidence","warning":W})
    wr(CFG/"open-holds.csv",f,hs);ac,f=rd(CFG/"acceptance-matrix.csv")
    for i,q in enumerate(["R251 purchase gates accepted","R251 supplier responses accepted","R251 articles received/quarantined","R251 roles/instruments accepted","R251 hold points signed","R251 operations completed","R251 HSI evidence accepted","R251 teardown/disposition accepted"],90):ac.append({"acceptance_id":f"ACC-{i:02d}","criterion":q,"execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":"","warning":W})
    wr(CFG/"acceptance-matrix.csv",f,ac);st=json.loads((CFG/"package-status.json").read_text(encoding="utf-8"));st.update({"identifier":CID,"round":"R251","current_records":35,"supersession_records":22,"open_holds":65,"acceptance_rows":97,"first_shop_session":ID});(CFG/"package-status.json").write_text(json.dumps(st,indent=2)+"\n",encoding="utf-8");(CFG/"README.md").write_text(f"# {CID}\n\n> **{W}**\n\nR251 adds the fail-closed first-shop-session contract. Sixty-five holds and ninety-seven unexecuted acceptances remain.\n",encoding="utf-8")
    hh=[]
    for r in cur:p=ROOT/r["source_path"];hh.append({"source_path":r["source_path"],"sha256":sh(p),"role":r["role"],"warning":W})
    wr(CFG/"source-hash-register.csv",["source_path","sha256","role","warning"],hh);man(CFG)
    for p in CFG.iterdir():
        if p.is_file() and p.name!="file-manifest.csv":shutil.copy2(p,CFGR/p.name)
    (CFGR/"index.html").write_text(page("HR-V0 configuration reconciliation P0.15","Current identifiers and open holds after the R251 first-shop-session contract.",CFGR,["current-configuration-map.csv","supersession-map.csv","gate-impact.csv","open-holds.csv","acceptance-matrix.csv"]),encoding="utf-8");man(CFGR)
def main():package();config();print("Generated R251 first-shop-session and P0.15: purchase/session unauthorized; results blank")
if __name__=="__main__":main()
