#!/usr/bin/env python3
"""Freeze the R307 CAD-resident constrained high-order-curving candidate."""
from __future__ import annotations
import csv,hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];R297=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-seam-free-partition-p0.1";R300=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-seam-free-jacobian-mesh-p0.1";R306=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-constrained-curving-mesh-p0.1";R300_GEN=ROOT/"tools/generate_hr_v0_j2_c07_pe_seam_free_jacobian_mesh_p01.py";R298_GEN=ROOT/"tools/generate_hr_v0_j2_c07_pe_seam_free_mesh_p01.py";BASE_GEN=ROOT/"tools/generate_hr_v0_j2_c07_conformal_zone_mesh_p01.py";OUT=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-cad-curving-prereg-p0.1";RELEASE=ROOT/"release/hr-v0/j2-c07-pe-cad-curving-prereg-p0.1";IDENT="HR-V0-J2-C07-PE-CAD-CURVING-PREREG-P0.1";WARNING="PRELIMINARY - CAD-RESIDENT CONSTRAINED CURVING PREREGISTRATION ONLY - NOT APPROVED FOR PROCUREMENT, QUOTATION, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def write_csv(p:Path,data:list[dict[str,object]])->None:
    fields=[]
    for r in data:
        for f in r:
            if f not in fields:fields.append(f)
    with p.open("w",newline="",encoding="utf-8") as s:w=csv.DictWriter(s,fieldnames=fields,lineterminator="\n");w.writeheader();w.writerows(data)
def main()->int:
    r300=json.loads((R300/"analysis-status.json").read_text());r306=json.loads((R306/"analysis-status.json").read_text())
    if not r306["controlled_stop"] or r306["numerical_result_available"] or not r300["global_sicn_gate"] or not r300["monitored_zone_minimum_gate"]:raise RuntimeError("predecessor boundary")
    protocol={"identifier":IDENT,"round":"R307-PREREG","date":"2026-08-13","candidate_id":"R307-C07-CAD-RESIDENT-CONSTRAINED-HIGHORDER-V01","physical_geometry_change":False,"source_analysis_brep_sha256":sha(R297/"c07-pe-seam-free-analysis-partition.brep"),"source_r300_status_sha256":sha(R300/"analysis-status.json"),"source_r306_status_sha256":sha(R306/"analysis-status.json"),"transitive_generators":{"r300":sha(R300_GEN),"r298":sha(R298_GEN),"base":sha(BASE_GEN)},"execution_sequence":["regenerate the frozen R300 Frontal+Netgen linear mesh in the live R297 OCC model","require exact equality of linear element tags/connectivity/SICN/zone codes and coordinate equality within 1e-12 mm against retained R300","call setOrder(2)","map every linear corner bijectively within 0.1 mm","run HighOrder once with force=false, niter=1, C07-MATRIX only while OCC geometry remains live","restore every mapped linear corner within 1e-12 mm","retain optimized midsides only if every gate passes"],"acceptance":{"r300_linear_topology_and_quality_exact":True,"r300_linear_coordinate_max_delta_mm":1e-12,"corner_bijection_max_mm":0.1,"corner_restore_max_mm":1e-12,"element_connectivity_and_orientation_preserved":True,"q4_q6_q8_wrong_or_zero":0,"q4_q6_q8_normalized_floor_fail":0,"exact_exterior_facet_map_complete":True,"maximum_q8_surface_deviation_mm":0.005,"per_face_area_relative_error_max":0.0025,"loaded_area_relative_error_max":0.0025,"load_location_and_moment_relative_drift_max":0.001},"stop_rule":"one CAD-resident execution only; no optimizer, iteration, field or mesh tuning; retain pass, rejection or controlled stop","execution_started":False,"execution_completed":False,"exact_facet_revalidation_executed":False,"full_reference_domain_curved_jacobian_positive":False,"r279_c02_complete":False,"structural_solution_executed":False,"mesh_convergence_complete":False,"r278_h02_closed":False,"capacity_credit":False,"selected":False,"safety_credit":False,"work_authority":False,"warning":WARNING}
    if OUT.exists():shutil.rmtree(OUT)
    OUT.mkdir(parents=True);(OUT/"frozen-cad-curving-protocol.json").write_text(json.dumps(protocol,indent=2)+"\n");(OUT/"analysis-status.json").write_text(json.dumps(protocol,indent=2)+"\n");(OUT/"execution-provenance.json").write_text(json.dumps({"identifier":IDENT,"generator_sha256":sha(Path(__file__).resolve()),"r297_brep_sha256":protocol["source_analysis_brep_sha256"],"r300_status_sha256":protocol["source_r300_status_sha256"],"r306_status_sha256":protocol["source_r306_status_sha256"],"warning":WARNING},indent=2)+"\n")
    write_csv(OUT/"acceptance-register.csv",[{"gate":k,"required":v,"status":"NOT EXECUTED","warning":WARNING} for k,v in protocol["acceptance"].items()])
    (OUT/"README.md").write_text(f"# {IDENT}\n\n**{WARNING}**\n\nR307 moves the one constrained `HighOrder` operation from the stalled discrete-mesh R306 route into the live OCC/CAD-resident R300 generation pipeline. The physical part and analysis partition do not change. The regenerated linear mesh must first reproduce R300 exactly. No structural or physical-work authority follows from this preregistration or a future sampled pass.\n")
    html=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>R307 CAD-resident curving</title><style>body{{font:17px/1.55 system-ui;margin:0;background:#eaf7ff;color:#08244a}}main{{max-width:980px;margin:auto;padding:32px}}h1{{font-size:clamp(30px,5vw,54px)}}.warn{{padding:18px;background:#ffd34f;border:3px solid #08244a;font-weight:800}}table{{width:100%;border-collapse:collapse;background:white}}th,td{{font-size:16px;padding:12px;border:1px solid #37658f;text-align:left}}.scroll{{overflow:auto}}</style></head><body><main><p class="warn">{WARNING}</p><h1>R307 CAD-resident curving</h1><p>One frozen attempt. The R300 linear mesh must reproduce before optimization.</p><div class="scroll"><table><tr><th>Stage</th><th>Requirement</th></tr><tr><td>Geometry</td><td>Live R297 OCC; no physical change</td></tr><tr><td>Linear mesh</td><td>Exact R300 topology, quality and zone codes</td></tr><tr><td>Curving</td><td>HighOrder once on C07-MATRIX; restore all corners</td></tr><tr><td>Validation</td><td>Q4/Q6/Q8 plus exact facet/B-Rep/load checks</td></tr><tr><td>Authority</td><td>None</td></tr></table></div></main></body></html>''';(OUT/"index.html").write_text(html)
    manifest=[]
    for p in sorted(OUT.iterdir()):
        if p.name!="file-manifest.csv":manifest.append({"relative_path":p.name,"sha256":sha(p),"bytes":p.stat().st_size,"warning":WARNING})
    write_csv(OUT/"file-manifest.csv",manifest)
    if RELEASE.exists():shutil.rmtree(RELEASE)
    RELEASE.parent.mkdir(parents=True,exist_ok=True);shutil.copytree(OUT,RELEASE);print(json.dumps(protocol,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
