#!/usr/bin/env python3
"""Freeze the single R306 constrained high-order-curving candidate."""
from __future__ import annotations
import csv,hashlib,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];R300=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-seam-free-jacobian-mesh-p0.1";R305=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-rail-jacobian-disposition-p0.1";R287=ROOT/"mechanical/analysis/hr-v0-j2-c07-fidelity-remesh-evaluation-p0.1";OUT=ROOT/"mechanical/analysis/hr-v0-j2-c07-pe-constrained-curving-prereg-p0.1";RELEASE=ROOT/"release/hr-v0/j2-c07-pe-constrained-curving-prereg-p0.1";IDENT="HR-V0-J2-C07-PE-CONSTRAINED-CURVING-PREREG-P0.1";WARNING="PRELIMINARY - CONSTRAINED HIGH-ORDER CURVING PREREGISTRATION ONLY - NOT APPROVED FOR PROCUREMENT, QUOTATION, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def write_csv(p:Path,data:list[dict[str,object]])->None:
    fields=[]
    for r in data:
        for f in r:
            if f not in fields:fields.append(f)
    with p.open("w",newline="",encoding="utf-8") as s:w=csv.DictWriter(s,fieldnames=fields,lineterminator="\n");w.writeheader();w.writerows(data)
def main()->int:
    r300=json.loads((R300/"analysis-status.json").read_text());r305=json.loads((R305/"analysis-status.json").read_text());r287=json.loads((R287/"analysis-status.json").read_text())
    if not r305["r300_restored_as_next_method_baseline"] or not r300["global_sicn_gate"] or not r300["monitored_zone_minimum_gate"]:raise RuntimeError("baseline boundary")
    protocol={"identifier":IDENT,"round":"R306-PREREG","date":"2026-08-13","candidate_id":"R306-C07-R300-CONSTRAINED-HIGHORDER-V01","source_mesh":"R300 exact retained Tet10; no remesh","source_mesh_gzip_sha256":sha(R300/"c07-conformal-zone-mesh.msh.gz"),"source_raw_linear_sha256":sha(R300/"raw-linear-mesh.npz"),"source_raw_tet10_sha256":sha(R300/"raw-tet10-mesh.npz"),"r300_status_sha256":sha(R300/"analysis-status.json"),"r305_status_sha256":sha(R305/"analysis-status.json"),"operation":{"gmsh_method":"HighOrder","force":False,"niter":1,"dim_tags":"C07-MATRIX volume only","corner_mapping_tolerance_mm":0.1,"corner_restore_tolerance_mm":1e-12,"restore_every_pre-operation_linear_corner":True,"retain_optimized_midsides":True},"acceptance":{"element_connectivity_and_orientation_preserved":True,"all_linear_corner_coordinates_restored_max_mm":1e-12,"global_and_zone_sicn_exactly_unchanged":True,"q4_q6_q8_wrong_or_zero":0,"q4_q6_q8_normalized_floor_fail":0,"exact_exterior_facet_map_complete":True,"maximum_q8_surface_deviation_mm":0.005,"per_face_area_relative_error_max":0.0025,"loaded_area_relative_error_max":0.0025,"load_location_and_moment_relative_drift_max":0.001},"reference_r287_surface_deviation_mm":r287["maximum_q8_surface_deviation_mm"],"stop_rule":"one execution only; no optimizer/iteration tuning; retain pass or rejection; no structural execution until separately dispositioned","mesh_executed":False,"exact_facet_revalidation_executed":False,"structural_solution_executed":False,"r279_c02_complete":False,"r278_h02_closed":False,"capacity_credit":False,"selected":False,"safety_credit":False,"work_authority":False,"warning":WARNING}
    if OUT.exists():shutil.rmtree(OUT)
    OUT.mkdir(parents=True);(OUT/"frozen-constrained-curving-protocol.json").write_text(json.dumps(protocol,indent=2)+"\n");(OUT/"analysis-status.json").write_text(json.dumps(protocol,indent=2)+"\n")
    (OUT/"execution-provenance.json").write_text(json.dumps({"identifier":IDENT,"generator_sha256":sha(Path(__file__).resolve()),"r300_status_sha256":sha(R300/"analysis-status.json"),"r305_status_sha256":sha(R305/"analysis-status.json"),"r287_status_sha256":sha(R287/"analysis-status.json"),"warning":WARNING},indent=2)+"\n")
    (OUT/"README.md").write_text(f"# {IDENT}\n\n**{WARNING}**\n\nR306 freezes one no-remesh constrained `HighOrder` optimization of the R300 C07-MATRIX. Every pre-operation linear corner must be restored exactly; optimized midsides may be retained only if Q4/Q6/Q8, exact facet mapping, B-Rep deviation, per-face area and load-geometry gates all pass. Full-domain positivity, R279-C02, structural convergence, H02, capacity and all work authority remain open.\n")
    rows=[{"gate":k,"required":json.dumps(v,separators=(",",":")) if isinstance(v,(dict,list)) else v,"status":"NOT EXECUTED","warning":WARNING} for k,v in protocol["acceptance"].items()];write_csv(OUT/"acceptance-register.csv",rows)
    html=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>R306 constrained curving</title><style>body{{font:17px/1.55 system-ui;margin:0;color:#08244a;background:#eef8ff}}main{{max-width:960px;margin:auto;padding:32px}}h1{{font-size:clamp(30px,5vw,54px)}}.warn{{background:#ffd24a;padding:18px;border:3px solid #08244a;font-weight:800}}table{{width:100%;border-collapse:collapse;background:white}}th,td{{padding:12px;border:1px solid #37658f;text-align:left;font-size:16px}}.scroll{{overflow:auto}}</style></head><body><main><p class="warn">{WARNING}</p><h1>R306 constrained high-order curving</h1><p>One frozen operation on the R300 mesh. No remesh, tuning, structural solve or work authority.</p><div class="scroll"><table><tr><th>Operation</th><th>Frozen value</th></tr><tr><td>Optimizer</td><td>HighOrder, one iteration, C07-MATRIX only</td></tr><tr><td>Corners</td><td>Restore every linear corner within 1e-12 mm</td></tr><tr><td>Curved checks</td><td>Q4/Q6/Q8 plus exact B-Rep facet/load revalidation</td></tr><tr><td>Authority</td><td>None</td></tr></table></div></main></body></html>''';(OUT/"index.html").write_text(html)
    manifest=[]
    for p in sorted(OUT.iterdir()):
        if p.name!="file-manifest.csv":manifest.append({"relative_path":p.name,"sha256":sha(p),"bytes":p.stat().st_size,"warning":WARNING})
    write_csv(OUT/"file-manifest.csv",manifest)
    if RELEASE.exists():shutil.rmtree(RELEASE)
    RELEASE.parent.mkdir(parents=True,exist_ok=True);shutil.copytree(OUT,RELEASE);print(json.dumps(protocol,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
