"""Controlled candidate decompositions for the 66 R141 compound requirements."""

DECOMPOSITIONS = {
    "SYS-001": [
        "HR-V0 shall be fixed to the accepted bench interface.",
        "HR-V0 shall have exactly two powered arm rotation axes.",
        "HR-V0 shall have exactly one powered gripper axis.",
    ],
    "SYS-002": [
        "HR-V0 shall transfer exactly one controlled soft-foam object per accepted cycle.",
        "The accepted handoff object mass including measurement uncertainty shall not exceed 100 g.",
        "Each accepted principal handoff-object dimension including measurement uncertainty shall be from 40 mm through 70 mm.",
    ],
    "SYS-004": [
        "Automatic tool-center speed shall not exceed 0.15 m/s in any released pose.",
        "The controller shall derive pose-dependent joint-rate limits from the commanded kinematics.",
        "Every automatic joint-rate command shall also remain at or below 30 deg/s.",
        "Verification of the 30 deg/s joint-rate ceiling shall not substitute for verification of the 0.15 m/s tool-center limit.",
    ],
    "SYS-005": [
        "Setup motion shall require continuous hold-to-run actuation.",
        "Setup joint speed shall not exceed 10 deg/s.",
    ],
    "SYS-006": [
        "The released system operating location shall be indoors.",
        "The released system operating ambient shall remain from 18 deg C through 28 deg C.",
        "The released system operating environment shall remain dry and noncondensing.",
    ],
    "SAFE-003": [
        "Each control-loss stop credited with reducing risk shall have a qualified ISO 12100 risk determination.",
        "Each control-loss stop credited with reducing risk shall have a separately validated ISO 13849-1:2023 or IEC 62061 integrity allocation.",
        "The ordinary HR-V0 heartbeat controller shall receive zero safety credit.",
        "HR-30 shall select a safety-rated control-loss architecture before motion release.",
        "Any HR-V0 configuration whose fixed guard cannot contain assumed watchdog failure shall select a safety-rated control-loss architecture before motion release.",
        "The ordinary HR-V0 heartbeat relays shall receive zero safety credit.",
        "The ordinary HR-V0 heartbeat drivers shall receive zero safety credit.",
        "The ordinary HR-V0 heartbeat firmware shall receive zero safety credit.",
        "The ordinary HR-V0 bus watchdog shall receive zero safety credit.",
        "HR-30 shall validate its selected safety-rated control-loss architecture before motion release.",
        "Any HR-V0 configuration whose fixed guard cannot contain assumed watchdog failure shall validate its selected safety-rated control-loss architecture before motion release.",
    ],
    "SAFE-004": [
        "Fixed shielding shall be installed before any powered HR-V0 fixture test.",
        "A controlled 600 mm exclusion boundary shall be established before any powered HR-V0 fixture test.",
    ],
    "SAFE-007": [
        "Each powered joint shall have independently enforced software limits.",
        "Each powered joint shall have mechanical hard stops that engage before any cable contact.",
        "Each powered joint shall have mechanical hard stops that engage before any shield contact.",
    ],
    "SAFE-008": [
        "Restart eligibility after a safety or diagnostic dropout shall require removal of the initiating cause.",
        "Restart eligibility after a safety or diagnostic dropout shall require a valid monitored physical RESET action.",
        "Restart eligibility after RESET shall require a later distinct physical ARM action.",
        "RESET shall not command torque.",
        "Motion after a safety or diagnostic dropout shall require a fresh validated trajectory.",
        "RESET shall not command motion.",
        "ARM shall not command torque.",
        "ARM shall not command motion.",
    ],
    "ELEC-001": [
        "The actuator-power domain shall have protection independent of the safety-control-power domain.",
        "The safety-control-power domain shall have protection independent of the compute-power domain.",
        "The compute-power domain shall have protection independent of the actuator-power domain.",
    ],
    "ELEC-003": [
        "Each actuator-power branch shall have separately selected branch protection.",
        "Each actuator-power-branch conductor shall be rated for the verified application load.",
        "Each actuator-power-branch connector shall be rated for the verified application load.",
        "Each actuator-power branch shall have coordinated branch protection.",
        "Each actuator-power-branch conductor shall be rated for the verified installation conditions.",
        "Each actuator-power-branch connector shall be rated for the verified installation conditions.",
    ],
    "ELEC-004": [
        "Each exposed mains terminal shall be inaccessible without a tool.",
        "Each conductive enclosure requiring protective bonding shall be protectively earthed by the released implementation.",
        "Each conductive machine structure requiring protective bonding shall be protectively earthed by the released implementation.",
    ],
    "CTRL-003": [
        "Loss of required communication shall cause the released fault response.",
        "A released limit violation shall cause the released fault response.",
        "A released overtemperature condition shall cause the released fault response.",
        "A released overcurrent condition shall cause the released fault response.",
        "Each CTRL-003 fault response shall latch until its released recovery sequence completes.",
    ],
    "CTRL-004": [
        "Command state shall be logged at 100 Hz or faster during released motion.",
        "Feedback state shall be logged at 100 Hz or faster during released motion.",
        "Each CTRL-004 log record shall bind the active configuration hash.",
        "Each CTRL-004 log stream shall retain a released timebase record.",
        "Each CTRL-004 log stream shall retain a released synchronization record.",
    ],
    "THERM-001": [
        "Arm-actuator case temperature shall remain below the provisional 65 deg C limit during the validated duty cycle at the released ambient condition.",
        "Gripper-actuator case temperature shall remain below the provisional 60 deg C limit during the validated duty cycle at the released ambient condition.",
        "Power-conductor temperature rise shall remain below 20 deg C during the validated duty cycle at the released ambient condition.",
    ],
    "GRIP-002": [
        "The HR-V0 gripper mechanism shall use the controlled ROBOTIS OpenMANIPULATOR-X mechanism subset.",
        "The HR-V0 gripper shall use broad compliant object-contact pads.",
        "A fixed local gripper guard shall prevent access to the actuator-frame crank-linkage pinch zone.",
        "A fixed local gripper guard shall prevent access to the rail pinch zones.",
        "HR-V0 shall not perform a human handoff under this release.",
    ],
    "SAFE-010": [
        "A fixed tool-removable enclosure shall be installed before any actuator connection.",
        "The enclosure inner boundary shall remain outside the released three-dimensional swept volume in every permitted pose and fault case.",
        "The enclosure inner boundary shall remain outside the released worst-case stopping-travel volume in every permitted pose and fault case.",
        "The enclosure inner boundary shall remain outside the released maximum-payload extent in every permitted pose and fault case.",
        "The enclosure inner boundary shall remain outside the released build-and-calibration tolerance extent in every permitted pose and fault case.",
        "The enclosure shall preserve the released minimum clearance from the union of all SAFE-010 extents.",
    ],
    "SAFE-011": [
        "A fixed receiver or catch shall contain the permitted foam object after commanded release from every released pose.",
        "A fixed receiver or catch shall contain the permitted foam object after gripper fault from every released pose.",
        "A fixed receiver or catch shall contain the permitted foam object after actuator-power loss from every released pose.",
        "The contained object shall not escape into an accessible area during any released SAFE-011 case.",
    ],
    "MECH-001": [
        "Each moving HR-V0 cable shall have a controlled route.",
        "Each moving HR-V0 cable shall have controlled strain relief.",
        "Each moving HR-V0 cable shall have a controlled service loop.",
        "Each moving HR-V0 cable shall remain within released bend limits.",
        "Each moving HR-V0 cable shall have released abrasion protection.",
        "Each moving HR-V0 cable shall remain clear of hard stops throughout the complete mechanical range.",
        "Each moving HR-V0 connector shall have a controlled route.",
        "Each moving HR-V0 cable shall have controlled retention.",
        "Each moving HR-V0 connector shall have controlled strain relief.",
        "Each moving HR-V0 connector shall have controlled retention.",
        "Each moving HR-V0 cable shall remain within released twist limits.",
        "Each moving HR-V0 connector shall have released abrasion protection.",
        "Each moving HR-V0 cable shall remain clear of pinch points throughout the complete mechanical range.",
        "Each moving HR-V0 cable shall remain clear of guards throughout the complete mechanical range.",
        "Each moving HR-V0 cable shall remain clear of payloads throughout the complete mechanical range.",
        "Each moving HR-V0 connector shall remain clear of hard stops throughout the complete mechanical range.",
        "Each moving HR-V0 connector shall remain clear of pinch points throughout the complete mechanical range.",
        "Each moving HR-V0 connector shall remain clear of guards throughout the complete mechanical range.",
        "Each moving HR-V0 connector shall remain clear of payloads throughout the complete mechanical range.",
    ],
    "VER-001": [
        "The released HR-V0 endurance run shall attempt exactly 100 fixture handoffs.",
        "The released HR-V0 endurance run shall complete at least 99 successful fixture handoffs.",
        "The released HR-V0 endurance run shall contain zero unsafe faults.",
    ],
    "CFG-001": [
        "Each test record shall identify the controlled CAD revision.",
        "Each test record shall identify the controlled wiring revision.",
        "Each test record shall identify the controlled firmware revision.",
        "Each test record shall identify the controlled calibration revision.",
        "Each test record shall identify the received actuator configuration revision.",
        "Each test record shall identify the controlled BOM revision.",
    ],
    "PROD-001": [
        "The HR-30 neutral-pose drawing height shall be 762 mm nominal.",
        "The measured height of every released HR-30 shell configuration shall remain from 740 mm through 800 mm.",
    ],
    "PROD-002": [
        "The HR-30 tethered-mass design target shall be 8.0 kg.",
        "The measured HR-30 tethered mass shall not exceed 10.0 kg.",
    ],
    "PROD-005": [
        "The full-height robot shall remain restrained throughout HR-30B, HR-30C and HR-30D testing.",
        "The full-height robot shall operate untethered only after the HR-30W release gate is approved.",
    ],
    "PROD-006": [
        "Each external cover edge shall have a radius of at least 3 mm.",
        "External covers shall prevent normal access to powered pinch points.",
    ],
    "PROD-008": [
        "HR-30A actuator power shall be supplied through a tether at extra-low voltage.",
        "HR-30A shall contain no onboard battery.",
    ],
    "PROD-009": [
        "The actuator-power state shall be visibly distinguishable from at least 3 m.",
        "The machine-fault state shall be visibly distinguishable from at least 3 m.",
    ],
    "PROD-010": [
        "Any enabled camera-recording capability shall have a visible privacy indication.",
        "The privacy indication shall be driven by camera hardware power state rather than application software state.",
    ],
    "LEG-001": [
        "Each powered leg-joint actuator shall pass its released load test before the joint is enabled.",
        "Each powered leg-joint actuator shall pass its released thermal test before the joint is enabled.",
        "Each powered leg-joint brake or power-loss strategy shall pass its released test before the joint is enabled.",
        "Each powered leg-joint structure shall pass its released proof before the joint is enabled.",
        "Each powered leg-joint restraint interface shall pass its released proof before the joint is enabled.",
    ],
    "LEG-002": [
        "Untethered level-floor walking shall remain the required HR-30W end-state.",
        "Untethered level-floor walking shall not begin until HR-30D slack-tether acceptance passes.",
    ],
    "WALK-002": [
        "HR-30W shall start from the released standing state without external support.",
        "HR-30W shall walk 25 m at a speed from 0.10 m/s through 0.14 m/s.",
        "HR-30W shall stop within two steps after the released stop command.",
        "HR-30W shall remain standing after the WALK-002 stop.",
        "Any walking speed above 0.14 m/s shall require a later released torque-speed validation.",
        "Any walking speed above 0.14 m/s shall require a later released gait validation.",
    ],
    "WALK-003": [
        "HR-30W shall turn 90 degrees left within five steps without external support.",
        "HR-30W shall turn 90 degrees right within five steps without external support.",
    ],
    "WALK-004": [
        "HR-30W shall complete 30 minutes of cumulative walking in the released test campaign.",
        "HR-30W shall remain within released thermal limits throughout the WALK-004 campaign.",
        "HR-30W shall remain within released current limits throughout the WALK-004 campaign.",
        "HR-30W shall remain within released voltage limits throughout the WALK-004 campaign.",
        "HR-30W shall remain within released energy limits throughout the WALK-004 campaign.",
    ],
    "WALK-005": [
        "The HR-30D overhead tether shall remain slack during released walking when no fall arrest is occurring.",
        "The HR-30D overhead tether shall carry less than 2 percent of measured robot weight when no fall arrest is occurring.",
    ],
    "WALK-006": [
        "Each HR-30 leg shall provide one active hip-yaw axis.",
        "Each HR-30 leg shall provide one active hip-roll axis.",
        "Each HR-30 leg shall provide one active hip-pitch axis.",
        "Each HR-30 leg shall provide one active knee-pitch axis.",
        "Each HR-30 leg shall provide one active ankle-pitch axis.",
        "Each HR-30 leg shall provide one active ankle-roll axis.",
    ],
    "WALK-007": [
        "Pelvis-attitude estimation shall update at 800 Hz or faster during released operation.",
        "Foot-force estimation shall update at 500 Hz or faster during released operation.",
        "Foot center-of-pressure estimation shall update at 500 Hz or faster during released operation.",
    ],
    "WALK-008": [
        "Failure of the Linux high-level process shall not prevent the real-time state estimator from reaching the released response.",
        "Failure of the Linux high-level process shall not prevent the real-time stabilizer from reaching the released response.",
        "The released WALK-008 response shall be continued safe operation or the released stop.",
    ],
    "WALK-009": [
        "The HR-30W onboard battery shall be professionally assembled for the released configuration.",
        "The HR-30W onboard battery shall include released pack-level protection.",
        "The HR-30W onboard battery shall include a coordinated pack-level fuse.",
        "The HR-30W onboard battery shall include a service disconnect.",
        "The HR-30W onboard battery shall include a coordinated precharge function.",
        "The HR-30W onboard battery shall provide independent pack telemetry.",
    ],
    "WALK-011": [
        "The fall predictor shall evaluate released attitude input.",
        "The fall predictor shall evaluate released angular-rate input.",
        "The fall predictor shall evaluate released support-force input.",
        "The fall predictor shall evaluate released joint-tracking input.",
        "The fall predictor shall evaluate released bus-health input.",
        "The fall predictor shall evaluate released supply-state input.",
        "The fall predictor shall command the released protective response within the released lead-time threshold.",
        "The released fall-prediction lead-time threshold shall exceed measured protective-response latency by the released margin.",
        "The numeric fall-prediction lead time shall remain a release-blocking selection until validated.",
        "The fall-prediction detection-rate acceptance value shall remain a release-blocking selection until validated.",
        "The fall-prediction false-positive acceptance value shall remain a release-blocking selection until validated.",
    ],
    "STANCE-001": [
        "Both HR-30C feet shall remain in contact with the released support surface during STANCE-001 acceptance.",
        "The two feet shall support 100 percent of measured static robot weight during STANCE-001 acceptance.",
        "The STANCE-001 load condition shall be maintained for 120 seconds.",
        "The connected restraint shall supply no sustained support during STANCE-001 acceptance.",
    ],
    "STANCE-002": [
        "HR-30C shall complete exactly 100 commanded bilateral weight shifts during STANCE-002 acceptance.",
        "Both feet shall remain in contact throughout each accepted STANCE-002 shift.",
        "Each STANCE-002 shift shall remain within released force limits.",
        "Each STANCE-002 shift shall remain within released attitude limits.",
        "Each STANCE-002 shift shall remain within released joint-tracking limits.",
        "Each STANCE-002 shift shall remain within released thermal limits.",
        "Each STANCE-002 shift shall remain within released current limits.",
        "Each STANCE-002 shift shall remain within released control-deadline limits.",
    ],
    "STANCE-003": [
        "Loss of valid planner state during HR-30C stance shall produce the released restrained response.",
        "Loss of sensor validity during HR-30C stance shall produce the released restrained response.",
        "Loss of a required control deadline during HR-30C stance shall produce the released restrained response.",
        "Loss of supply health during HR-30C stance shall produce the released restrained response.",
        "Each STANCE-003 response shall latch a restart-required fault.",
    ],
    "STANCE-004": [
        "HR-30C powered-stance testing shall not begin until HR-30B acceptance is approved.",
        "HR-30C powered-stance testing shall not begin until W0 actuator evidence is approved.",
        "HR-30C powered-stance testing shall not begin until W1 joint evidence is approved.",
        "HR-30C powered-stance testing shall not begin until restraint proof is approved.",
        "HR-30C powered-stance testing shall not begin until sensor calibration is approved.",
        "HR-30C powered-stance testing shall not begin until every enabled-axis qualification record is approved.",
    ],
    "PROD-011": [
        "The released operating boundary shall identify the system as adult-operated experimental robotic machinery.",
        "The released operating boundary shall state that the system is not a toy.",
        "The released operating boundary shall state that the system is not approved for unsupervised consumer use.",
        "The released operating boundary shall state that legal classification remains unresolved until accepted applicability evidence exists.",
    ],
    "MASS-001": [
        "Each full-body configuration shall have a controlled part-level mass ledger.",
        "Each full-body configuration shall have a controlled part-level inertia ledger.",
        "Each full-body mass ledger shall distinguish target values from estimated values.",
        "Each full-body mass ledger shall distinguish estimated values from measured values.",
        "Each full-body configuration shall report assembly center of mass.",
        "Each full-body configuration shall report whole-body center of mass.",
        "Each full-body configuration shall report assembly inertia in the released frame.",
        "Each full-body configuration shall report whole-body inertia in the released frame.",
    ],
    "MASS-002": [
        "HR-V0 moving-assembly mass excluding the fixed shoulder actuator and base shall not exceed 0.75 kg.",
        "The exact HR-V0 moving assembly shall have a controlled part-level mass ledger.",
        "The HR-V0 moving-mass ledger shall distinguish CAD mass from supplier mass.",
        "The HR-V0 moving-mass ledger shall distinguish supplier mass from measured mass.",
        "The HR-V0 moving-mass ledger shall report each part local center of mass.",
        "The HR-V0 moving-mass ledger shall report each part inertia in its controlled local frame.",
    ],
    "CTRL-005": [
        "Each inter-controller message shall carry a monotonic sequence number.",
        "Each inter-controller message shall carry a source timestamp.",
        "Each inter-controller message shall carry a validity deadline.",
        "Each inter-controller message shall carry the sender state.",
        "Each inter-controller message shall carry the active configuration hash.",
        "A receiver shall reject a stale inter-controller message.",
        "A receiver shall reject a duplicate inter-controller message.",
        "A receiver shall reject an out-of-order inter-controller message.",
        "A receiver shall reject an inter-controller message with a mismatched configuration hash.",
    ],
    "WALK-013": [
        "Each externally reduced leg joint shall use output-side absolute position sensing or a reviewed equivalent.",
        "Each WALK-013 sensing implementation shall detect output slip beyond the released threshold.",
        "Each WALK-013 sensing implementation shall detect backlash beyond the released threshold.",
        "Each WALK-013 sensing implementation shall detect lost output calibration.",
        "Each WALK-013 sensing implementation shall detect motor-to-output disagreement beyond the released threshold.",
    ],
    "WALK-014": [
        "Each segmented joint bus shall demonstrate the released command schedule.",
        "Each segmented joint bus shall demonstrate the released feedback schedule.",
        "Each segmented joint bus shall have a byte-level packet budget for the released schedule.",
        "Each segmented joint bus shall have measured worst-case latency for the released traffic and fault cases.",
        "Each segmented joint bus shall have measured worst-case jitter for the released traffic and fault cases.",
        "Each segmented joint bus shall have measured worst-case utilization for the released traffic and fault cases.",
        "Each segmented joint bus shall demonstrate its released response to injected fault traffic.",
    ],
    "SAFE-009": [
        "Each powered full-body development phase shall define its response to sudden drive-energy loss.",
        "Each powered full-body development phase shall test sudden drive-energy loss in every released pose.",
        "Each powered full-body development phase shall test sudden drive-energy loss in every released mode.",
        "A full-body phase shall not reduce restraint dependence until its SAFE-009 response evidence is accepted.",
    ],
    "CFG-002": [
        "A configuration mismatch shall inhibit drive enable.",
        "A calibration mismatch shall inhibit drive enable.",
        "A polarity mismatch shall inhibit drive enable.",
        "A mirrored-joint mismatch shall inhibit drive enable.",
        "Each CFG-002 mismatch shall latch a recorded fault.",
    ],
    "GOV-001": [
        "Each requirement shall identify an accountable owner before design-review approval.",
        "Each requirement shall identify its acceptance evidence before design-review approval.",
        "Each requirement shall identify an approver before design-review approval.",
        "Each requirement shall have controlled change history before design-review approval.",
        "Each risk shall identify an accountable owner before design-review approval.",
        "Each risk shall identify its acceptance evidence before design-review approval.",
        "Each risk shall identify an approver before design-review approval.",
        "Each risk shall have controlled change history before design-review approval.",
        "Each release gate shall identify an accountable owner before design-review approval.",
        "Each release gate shall identify its acceptance evidence before design-review approval.",
        "Each release gate shall identify an approver before design-review approval.",
        "Each release gate shall have controlled change history before design-review approval.",
    ],
    "CTRL-006": [
        "Before torque-enable request the supervisor shall verify received actuator identity against the released configuration.",
        "Before torque-enable request the supervisor shall verify actuator firmware identity against the released configuration.",
        "Before torque-enable request the supervisor shall verify actuator ID against the released configuration.",
        "Before torque-enable request the supervisor shall verify actuator operating mode against the released configuration.",
        "Before torque-enable request the supervisor shall verify startup-torque configuration against the released configuration.",
        "Before torque-enable request the supervisor shall verify torque-on-goal-update configuration against the released configuration.",
        "Before torque-enable request the supervisor shall verify actuator current limit against the released configuration.",
        "Before torque-enable request the supervisor shall verify goal-current bound against the released configuration.",
        "Before torque-enable request the supervisor shall verify the hardware-error state against the released acceptance state.",
        "Before torque-enable request the supervisor shall verify that actuator torque is off.",
        "Any failed CTRL-006 verification shall inhibit torque enable.",
        "Any failed CTRL-006 verification shall latch a recorded fault.",
        "The internal actuator current limit shall not substitute for external branch-current evidence.",
        "The internal actuator current limit shall not substitute for connector thermal evidence.",
        "The internal actuator current limit shall not substitute for protection-coordination evidence.",
    ],
    "CTRL-007": [
        "The ordinary HR-V0 heartbeat watchdog shall receive zero safety credit.",
        "The ordinary HR-V0 heartbeat watchdog shall be treated only as a diagnostic power-removal demand.",
        "The candidate heartbeat-loss detection interval shall not exceed 300 ms before relay and contactor delays.",
        "Heartbeat restoration shall not bypass monitored physical RESET.",
        "Heartbeat restoration shall not bypass the later distinct physical ARM action.",
        "The safety risk assessment shall assume that the ordinary heartbeat diagnostic can fail to operate.",
    ],
    "CFG-003": [
        "The HR-V0 release BOM shall enumerate every purchased item.",
        "The HR-V0 release BOM shall enumerate every fabricated item.",
        "The HR-V0 release BOM shall enumerate every included-kit item.",
        "The HR-V0 release BOM shall enumerate every harness item.",
        "The HR-V0 release BOM shall enumerate every software-image item.",
        "The HR-V0 release BOM shall enumerate every configuration-critical item.",
        "Each HR-V0 release-BOM row shall state exact quantity.",
        "Each HR-V0 release-BOM row shall state exact order-code status.",
        "Each HR-V0 release-BOM row shall state primary-source status.",
        "Each HR-V0 release-BOM row shall state application-evidence status.",
        "Each HR-V0 release-BOM row shall state a receiving or closure route.",
        "Each unresolved HR-V0 release-BOM field shall remain SELECTION REQUIRED.",
    ],
    "MECH-002": [
        "The HR-V0 mechanical release shall define one controlled bench-to-object datum chain.",
        "The HR-V0 mechanical release shall enumerate every assembly component.",
        "The HR-V0 mechanical release shall enumerate every mechanical interface.",
        "The HR-V0 mechanical release shall define exact profile cut lengths.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved dimension.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved fastener.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved fit.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved guard boundary.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved stop boundary.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved cable boundary.",
        "The HR-V0 mechanical release shall identify closure evidence for each unresolved anchor boundary.",
        "Generated HR-V0 assembly views shall agree with the released native CAD.",
        "Generated HR-V0 assembly views shall agree with the released system BOM.",
    ],
    "MECH-003": [
        "Each HR-V0 T-slot frame joint shall identify the exact bracket order code.",
        "Each HR-V0 T-slot frame joint shall identify every mounting-hardware order code.",
        "Each HR-V0 T-slot frame joint shall identify installed quantity.",
        "Each HR-V0 T-slot frame joint shall identify installed orientation.",
        "Each HR-V0 T-slot frame joint shall have a controlled load-path screen.",
        "Each HR-V0 T-slot frame joint shall have a controlled torque-development method.",
        "Each HR-V0 T-slot frame joint shall have an accepted receiving record before assembly acceptance.",
        "Each HR-V0 T-slot frame joint shall have an accepted proof record before assembly acceptance.",
        "Each HR-V0 T-slot frame joint shall have an inspection mark before assembly acceptance.",
        "Each HR-V0 T-slot frame joint shall have a controlled fastener-reuse rule.",
        "Each HR-V0 T-slot frame joint shall have a qualified mechanical disposition before assembly acceptance.",
        "Absent MECH-003 physical evidence shall inhibit assembly acceptance.",
    ],
    "MECH-004": [
        "The HR-V0 bench interface shall identify one exact surveyed bench before release.",
        "The HR-V0 bench interface shall have documented site-owner permission before release.",
        "The HR-V0 bench interface shall record substrate construction before release.",
        "The HR-V0 bench interface shall record substrate thickness before release.",
        "The HR-V0 bench interface shall record all applicable edge distances before release.",
        "The HR-V0 bench interface shall record top-side access before release.",
        "The HR-V0 bench interface shall record underside access before release.",
        "The HR-V0 bench interface shall identify exact anchor order codes before release.",
        "The HR-V0 bench interface shall identify exact bolt order codes before release.",
        "The HR-V0 bench interface shall identify exact washer order codes before release.",
        "The HR-V0 bench interface shall identify exact backing-part order codes before release.",
        "The HR-V0 bench-interface analysis shall calculate anchor shear load.",
        "The HR-V0 bench-interface analysis shall calculate anchor tension load.",
        "The HR-V0 bench-interface analysis shall calculate overturning load.",
        "The HR-V0 bench-interface analysis shall calculate substrate bearing load.",
        "The HR-V0 bench-interface analysis shall calculate substrate pull-through load.",
        "The HR-V0 bench-interface analysis shall calculate bench-support loads.",
        "The HR-V0 bench-interface installation shall use a controlled installation-torque requirement.",
        "The HR-V0 bench-interface release shall define numerical proof criteria.",
        "The HR-V0 bench-interface installation shall carry controlled inspection marks.",
        "The HR-V0 bench interface shall have a qualified mechanical disposition before release.",
        "Absent or changed MECH-004 site evidence shall inhibit assembly acceptance.",
        "Absent or changed MECH-004 site evidence shall inhibit energization acceptance.",
    ],
    "MECH-005": [
        "The HR-V0 arm architecture shall use exact manufacturer-coordinate actuator geometry.",
        "The HR-V0 arm architecture shall use exact manufacturer-coordinate frame geometry.",
        "The HR-V0 arm architecture shall define every controlled body frame.",
        "The HR-V0 arm architecture shall define every controlled output frame.",
        "The HR-V0 arm architecture shall define every controlled link transform.",
        "The HR-V0 arm architecture shall define every controlled gripper transform.",
        "The released native arm assembly shall prove J1 axis orientation.",
        "The released native arm assembly shall prove J2 axis orientation.",
        "The released native arm assembly shall prove J1-to-J2 axis parallelism.",
        "The released native arm assembly shall prove controlled link lengths.",
        "The released native arm assembly shall prove collision clearance over the released range.",
        "The released native arm assembly shall prove required tool access.",
        "The released native arm assembly shall define every fastener stack.",
        "The released native arm assembly shall prove required cable space.",
        "The released native arm assembly shall define the structural load path.",
        "The released native arm assembly shall close the released tolerance stack.",
        "Any superseded MECH-005 transform shall inhibit quotation.",
        "Any unresolved MECH-005 transform shall inhibit quotation.",
        "Any superseded MECH-005 transform shall inhibit fabrication.",
        "Any superseded MECH-005 transform shall inhibit assembly.",
        "Any superseded MECH-005 transform shall inhibit energization.",
        "Any unresolved MECH-005 transform shall inhibit fabrication.",
        "Any unresolved MECH-005 transform shall inhibit assembly.",
        "Any unresolved MECH-005 transform shall inhibit energization.",
    ],
    "MECH-006": [
        "The released HR-V0 J2 commanded limit shall remain below the first validated self-collision angle.",
        "The independent J2 mechanical hard stop shall remain below the first validated self-collision angle.",
        "The documented J2 collision margin shall exceed worst-case control-delay travel.",
        "The documented J2 collision margin shall exceed worst-case stopping overtravel.",
        "The documented J2 collision margin shall exceed worst-case backlash contribution.",
        "The documented J2 collision margin shall exceed worst-case compliance contribution.",
        "The documented J2 collision margin shall exceed worst-case build-tolerance contribution.",
        "The documented J2 collision margin shall exceed worst-case measurement-uncertainty contribution.",
        "The combined MECH-006 margin shall remain positive in every permitted payload, speed and fault case.",
        "An unmeasured MECH-006 margin shall inhibit actuator connection.",
        "A nonpositive MECH-006 margin shall inhibit actuator connection.",
        "An unmeasured MECH-006 margin shall inhibit energization.",
        "A nonpositive MECH-006 margin shall inhibit energization.",
    ],
    "COMM-001": [
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted commit.",
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted file manifest.",
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted BOM revision.",
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted ECAD revision.",
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted CAD revision.",
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted firmware revision.",
        "Before E2 control-only energization the complete unpowered HR-V0 article shall match one accepted procedure baseline.",
        "All required guards shall be installed before E2 control-only energization.",
        "All required torque witness marks shall be intact before E2 control-only energization.",
        "Every E2 deviation shall be closed or explicitly accepted by the accountable qualified reviewer before energization.",
    ],
    "COMM-002": [
        "A qualified electrical reviewer shall accept the exact site supply before any E2 source connection.",
        "A qualified electrical reviewer shall accept each exact external factory adapter before any E2 source connection.",
        "A qualified electrical reviewer shall accept the protective-earth treatment before any E2 source connection.",
        "A qualified electrical reviewer shall accept the insulation obligations before any E2 source connection.",
        "A qualified electrical reviewer shall accept the disconnect method before any E2 source connection.",
        "A qualified electrical reviewer shall accept the exact test instruments before any E2 source connection.",
        "A qualified electrical reviewer shall accept numerical E2 test limits for the as-built configuration before any source connection.",
    ],
    "COMM-003": [
        "Each HR-V0 extra-low-voltage conductor shall pass point-to-point continuity inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage terminal shall pass point-to-point continuity inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage connector shall pass point-to-point continuity inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage conductor shall pass polarity inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage conductor shall pass the released isolation-resistance inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage conductor shall pass the released no-backfeed inspection before E2 control power.",
        "Each COMM-003 inspection shall use the accepted ECAD as a comparison baseline.",
        "Each HR-V0 extra-low-voltage terminal shall pass polarity inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage connector shall pass polarity inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage terminal shall pass the released isolation-resistance inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage connector shall pass the released isolation-resistance inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage terminal shall pass the released no-backfeed inspection before E2 control power.",
        "Each HR-V0 extra-low-voltage connector shall pass the released no-backfeed inspection before E2 control power.",
        "Each COMM-003 inspection shall use the accepted as-built harness as a comparison baseline.",
    ],
    "COMM-004": [
        "E2 shall energize only the accepted 24 V safety-control source.",
        "The 12 V actuator source shall be physically absent throughout E2.",
        "Every actuator branch shall be disconnected throughout E2.",
        "Every disconnected actuator branch shall be covered throughout E2.",
        "Every actuator branch shall be verified at zero volts before the released E2 checks.",
        "The staged E2 safety-logic tests shall prove that no tested recovery condition causes automatic restart.",
        "E2 evidence shall claim no motion-validation credit.",
        "E2 evidence shall claim no stopping-distance-validation credit.",
        "E2 shall energize only the accepted 5.1 V compute source.",
        "Every actuator branch shall be verified at zero volts during the released E2 checks.",
    ],
    "COMM-005": [
        "Each E2 run shall have written configuration-specific authorization from the test director.",
        "Each E2 run shall have written configuration-specific authorization from a qualified electrical reviewer.",
        "Each E2 run shall have written configuration-specific authorization from a qualified functional-safety reviewer.",
        "Each E2 run shall have written configuration-specific authorization from an independent witness.",
        "Any prerequisite change during E2 shall revoke authorization.",
        "Any unexpected voltage during E2 shall revoke authorization.",
        "Any unauthorized state during E2 shall revoke authorization.",
        "Any expired calibration during E2 shall revoke authorization.",
        "Any open deviation during E2 shall revoke authorization.",
        "Any exclusion-zone breach during E2 shall revoke authorization.",
        "Any prerequisite change during E2 shall require controlled shutdown.",
        "Any unexpected voltage during E2 shall require controlled shutdown.",
        "Any unauthorized state during E2 shall require controlled shutdown.",
        "Any expired calibration during E2 shall require controlled shutdown.",
        "Any open deviation during E2 shall require controlled shutdown.",
        "Any exclusion-zone breach during E2 shall require controlled shutdown.",
    ],
    "CTRL-008": [
        "The HR-V0 DYNAMIXEL transport shall not open a device while any required received identity is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while any required current selection is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while calibration is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while the motion profile is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while voltage limits are unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while temperature limits are unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while operating-system selection is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while device-path selection is unresolved.",
        "After release the transport shall command torque off before actuator discovery.",
        "After release the transport shall verify the exact received device set before configuration.",
        "After release the transport shall configure actuators while torque remains off.",
        "After release the transport shall read back the released configuration while torque remains off.",
        "After release the transport shall enable torque only for one fresh supervisor trajectory whose configuration matches.",
        "After release the transport shall remove torque on any authority fault.",
        "After release the transport shall remove torque on any communication fault.",
        "After release the transport shall remove torque on any watchdog fault.",
        "After release the transport shall remove torque on any telemetry fault.",
        "After release the transport shall remove torque on any execution fault.",
        "After any CTRL-008 fault the transport shall not resume the prior target.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while calibration is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while the motion profile is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while voltage limits are unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while temperature limits are unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while operating-system selection is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not open a device while SDK selection is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while SDK selection is unresolved.",
        "The HR-V0 DYNAMIXEL transport shall not write a register while device-path selection is unresolved.",
        "After release the transport shall enable torque only for one fresh supervisor trajectory whose preconditions match.",
    ],
}
