#!/usr/bin/env python3
"""Publish R282 fail-closed J2 refinement protocol erratum and method evidence."""
from __future__ import annotations
import csv,hashlib,html,json,shutil,sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
CURVED=ROOT/"mechanical/analysis/hr-v0-j2-curved-tet10-prototype-p0.1";XCHK=ROOT/"mechanical/analysis/hr-v0-j2-backend-crosscheck-p0.1"
OUT=ROOT/"mechanical/analysis/hr-v0-j2-refinement-erratum-p0.1";REL=ROOT/"release/hr-v0/j2-refinement-erratum-p0.1"
CFG0=ROOT/"configuration/hr-v0-config-reconciliation-p0.45";CFG=ROOT/"configuration/hr-v0-config-reconciliation-p0.46";CFGREL=ROOT/"release/hr-v0/configuration-reconciliation-p0.46"
IDENT="HR-V0-J2-REFINEMENT-ERRATUM-P0.1";CFGID="HR-V0-CONFIG-REC-P0.46"
HISTORICAL_BASELINE_COMMIT="f271cbe4fb25ae70044103e88fce7fcfea976dea"
WARNING="PRELIMINARY - PROTOCOL CORRECTION AND NUMERICAL METHOD EVIDENCE ONLY - NOT APPROVED FOR PROCUREMENT, QUOTATION, FABRICATION, ASSEMBLY, CONNECTION, POWERED TESTING, MOTION, OR ENERGIZATION"

def rows(path):
    with path.open(newline="",encoding="utf-8-sig") as s:return list(csv.DictReader(s))
def write_csv(path,rec):
    path.parent.mkdir(parents=True,exist_ok=True)
    with path.open("w",newline="",encoding="utf-8") as s:
        fields=[]
        for r in rec:
            for k in r:
                if k not in fields:fields.append(k)
        w=csv.DictWriter(s,fieldnames=fields,lineterminator="\n");w.writeheader();w.writerows(rec)
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def manifest(directory):
    rec=[{"relative_path":p.relative_to(directory).as_posix(),"sha256":sha(p),"bytes":p.stat().st_size,"warning":WARNING} for p in sorted(directory.rglob("*")) if p.is_file() and p.name!="file-manifest.csv"]
    write_csv(directory/"file-manifest.csv",rec)
def table(rec):
    fields=[field for field in rec[0] if field != "warning"];return "<div class='scroll'><table><thead><tr>"+"".join(f"<th>{html.escape(k.replace('_',' '))}</th>" for k in fields)+"</tr></thead><tbody>"+"".join("<tr>"+"".join(f"<td>{html.escape(str(r.get(k,'')))}</td>" for k in fields)+"</tr>" for r in rec)+"</tbody></table></div>"

def main():
    for d in (OUT,REL,CFG,CFGREL):
        if d.exists():shutil.rmtree(d)
    OUT.mkdir(parents=True)
    freeze=[
      {"control_id":"R282-F01","subject":"moment datum/sign","frozen_definition":"d=(0,0,0) mm in each part-local STEP frame; M=sum/integral ((x-d) cross traction) dA; reactions use constrained-DOF physical coordinates; right-hand-rule components","acceptance":"force <=1e-8 and moment <=1e-6 normalized errors; applied/reaction resultants and all components retained","prior_gap":"datum and discrete reaction coordinates were not frozen","warning":WARNING},
      {"control_id":"R282-F02","subject":"C07 pocket-floor probes","frozen_definition":"floor y=8.005 mm; center (44,8.005,1), four probes (40,8.005,-15),(48,8.005,-15),(40,8.005,17),(48,8.005,17); normal +Y","acceptance":"exact field interpolation; fail closed if any point is outside exact CAD floor","prior_gap":"probe coordinates/normal absent","warning":WARNING},
      {"control_id":"R282-F03","subject":"quality histogram","frozen_definition":"SICN edges [0,.10,.20,.30,.40,.50,.60,.70,.80,.90,1.00]","acceptance":"count and fraction globally and separately in every monitored physical zone; signed Jacobian orientation screen at actual quadrature","prior_gap":"only two global aggregate screens were reported","warning":WARNING},
      {"control_id":"R282-F04","subject":"effective h","frozen_definition":"global h=(exact solid volume/tet count)^(1/3). For a clipped volume zone use h=(exact intersection volume / effective cell count)^(1/3), effective cell count=sum(intersection volume_i/full tet volume_i); surface analog uses exact intersection area and effective facet count=sum(intersection area_i/full facet area_i), exponent 1/2","acceptance":"freeze the exact intersection rule and domain; report actual metric-specific h. Boundary cells must be geometrically clipped, never included by centroid","prior_gap":"raw included-cell counts are mesh-dependent and nominal size alone is insufficient","warning":WARNING},
      {"control_id":"R282-F05","subject":"unequal-grid GCI","frozen_definition":"coarse c=L1, medium m=L2, fine f=L3; r_cm=h_c/h_m>1, r_mf=h_m/h_f>1; deltas dc_m=phi_c-phi_m and dm_f=phi_m-phi_f. For monotone nonzero sequence solve dc_m/dm_f = r_mf^p*(r_cm^p-1)/(r_mf^p-1). eps_cm=(phi_m-phi_c)/phi_m; eps_mf=(phi_f-phi_m)/phi_f; GCI_cm=1.25*abs(eps_cm)/(r_cm^p-1); GCI_mf=1.25*abs(eps_mf)/(r_mf^p-1); asymptotic ratio=GCI_cm/(r_mf^p*GCI_mf)","acceptance":"require same-sign nonzero deltas, r>1, 0.5<=p<=3.0, ratio 0.8..1.25 and fine GCI<=5%. Near-zero means abs(phi)<=max(1e-12 in metric units,1e-9*max(abs(phi_c),abs(phi_m),abs(phi_f))); any denominator near zero, sign crossing or oscillation is INVALID/OPEN and requires L4 or a frozen absolute-error metric","prior_gap":"unequal-grid equation/orientation/plausible p and near-zero behavior were not frozen","warning":WARNING},
      {"control_id":"R282-F06","subject":"stress statistics","frozen_definition":"evaluate stress at solver quadrature points and integrate directly with quadrature weights; do not replace by element-centroid/sample approximations","acceptance":"mean/RMS/p95 and raw maxima per exact frozen zone; raw maxima explicitly singular/non-capacity","prior_gap":"prototype used element means and sampled curve distance","warning":WARNING},
    ]
    zones=[
      {"zone_id":"C06-RR-PROFILE","definition":"exact B-Rep distance <=3 mm from named R2 rail/shoulder transition; split INBOARD/OUTBOARD and Y_FRONT/Y_BACK by closest exact curve parameter and y half","identity":"edge names/signatures must be frozen from STEP hash before execution","centroid_or_sample_substitute":"PROHIBITED","warning":WARNING},
      {"zone_id":"C06-RR-STEP","definition":"exact B-Rep distance <=3 mm from separately named thickness-step blend","identity":"exact edge signatures required; cannot reuse aggregate rail-root samples","centroid_or_sample_substitute":"PROHIBITED","warning":WARNING},
      {"zone_id":"C07-PE","definition":"exact 1 mm B-Rep band split into four R2 corner and four straight-edge identities","identity":"eight exact edge signatures required","centroid_or_sample_substitute":"PROHIBITED","warning":WARNING},
      {"zone_id":"HOLES","definition":"H1(-16,-8), H2(-16,+8), H3(+16,-8), H4(+16,+8), E1(0,-10), E2(0,+10), each with y=0 and y=9.525 rim identities and frozen offset bands","identity":"exact cylindrical face/end-curve intersections","centroid_or_sample_substitute":"PROHIBITED","warning":WARNING},
      {"zone_id":"C06/C07-GAUGE","definition":"C06 Z=18 mm and C07 X=34 mm exact solid-plane intersections; integrate traction and moment over exact cut polygons","identity":"fixed plane and part-local datum","centroid_or_sample_substitute":"PROHIBITED","warning":WARNING},
    ]
    architecture=[
      {"stage":"A","method":"global linear-geometry P1/P2 resource scout","purpose":"estimate DOF/nonzeros/conditioning only","required_raw_evidence":"STEP/script/runtime/parameter hashes; nodes/connectivity; element qualities/histograms; entity/facet/zone maps","credit":"NO CONVERGENCE/CAPACITY","warning":WARNING},
      {"stage":"B","method":"curved Tet10/P2-displacement global solve on L0/L1 where bounded","purpose":"establish correct geometry/order route and boundary transfer","required_raw_evidence":"matrix or reproducible assembly inputs; RHS; solution; reactions; true residual history; correction log","credit":"METHOD ONLY UNTIL ACCEPTED","warning":WARNING},
      {"stage":"C","method":"Saint-Venant checked global/local submodels for C06 and C07, independently refined through L3/L4","purpose":"avoid infeasible monolithic L3 while preserving fixed physical zones","required_raw_evidence":"cut-boundary displacement/traction transfer hashes; boundary-distance study; local/global energy and resultants","credit":"OPEN UNTIL INDEPENDENT REVIEW","warning":WARNING},
      {"stage":"D","method":"matrix-free or HPC global confirmation","purpose":"independent cross-check of final two accepted levels","required_raw_evidence":"hardware/runtime, solver/preconditioner, every residual/correction and resource observation","credit":"OPEN","warning":WARNING},
    ]
    write_csv(OUT/"protocol-freeze-register.csv",freeze);write_csv(OUT/"exact-zone-register.csv",zones);write_csv(OUT/"execution-architecture.csv",architecture)
    curved=json.loads((CURVED/"analysis-status.json").read_text(encoding="utf-8"));cross=json.loads((XCHK/"analysis-status.json").read_text(encoding="utf-8"))
    evidence=[{"evidence_id":"R282-E01","scope":"C06 curved Tet10 transfer","result":"PASS PROTOTYPE SCREEN","detail":"18,351/18,351 edges mapped; zero wrong-sign Jacobians at chosen quadrature","credit":"METHOD PROTOTYPE ONLY","warning":WARNING},{"evidence_id":"R282-E02","scope":"C07 curved Tet10 transfer","result":"FAIL PROTOTYPE SCREEN","detail":"26,209/26,209 edges mapped but 18 quadrature Jacobians have wrong/zero orientation; fraction 9.129455681564586e-05","credit":"NONE; CURVED ROUTE REQUIRES REPAIR","warning":WARNING},{"evidence_id":"R282-E03","scope":"coarse exact-CAD direct versus CG","result":"PASS PROJECT-OWNED NUMERICAL CROSS-CHECK","detail":"solution L2 difference 7.38244e-13; energy difference 1.08660e-12; displacement difference 6.63131e-13","credit":"BACKEND ONLY; REVIEW OPEN","warning":WARNING},{"evidence_id":"R282-E04","scope":"unit-cube affine elasticity patch","result":"PASS PROJECT-OWNED ANALYTIC REFERENCE","detail":"direct DOF error 1.66411e-16; CG DOF error 1.31693e-13; energy and resultant/moment gates pass","credit":"BACKEND/ASSEMBLY ONLY; REVIEW OPEN","warning":WARNING}]
    write_csv(OUT/"method-evidence-register.csv",evidence)
    errata=[
      {"erratum_id":"R282-ER01","historical_baseline_commit":HISTORICAL_BASELINE_COMMIT,"historical_artifact":"HR-V0-J2-NUMERICAL-BACKEND-P0.1","historical_claim":"C07 mesh method passes SICN quality / route enables L0-L3","correction":"Delaunay+Netgen L0 passed only two global SICN screens. Local-zone histograms and signed Jacobian screens were absent; full R279-C02 did not pass and defensible L0-L3 was not enabled.","configuration_action":"historical P0.1 bytes remain immutable; R282 controls current interpretation","warning":WARNING},
      {"erratum_id":"R282-ER02","historical_baseline_commit":HISTORICAL_BASELINE_COMMIT,"historical_artifact":"HR-V0-J2-C07-ITERATIVE-SOLVER-P0.1","historical_claim":"duplicate attempt ID and summarized/hard-coded correction provenance","correction":"attempt IDs are non-unique and raw per-iteration residual/correction history was not retained; no new provenance is inferred","configuration_action":"historical P0.1 bytes remain immutable; unique IDs and raw histories are mandatory for any P0.2 rerun","warning":WARNING},
      {"erratum_id":"R282-ER03","historical_baseline_commit":HISTORICAL_BASELINE_COMMIT,"historical_artifact":"R281 P2 wording","historical_claim":"P2 route","correction":"the solved route was P2 displacement on linear geometry, not curved P2 geometry","configuration_action":"current interpretation is P2-displacement / linear-geometry","warning":WARNING},
      {"erratum_id":"R282-ER04","historical_baseline_commit":HISTORICAL_BASELINE_COMMIT,"historical_artifact":"R281 package checkout representation","historical_claim":"repository checkout reproduces manifest-bound package bytes","correction":"four R281 JSON/README working artifacts require explicit CRLF checkout rules to reproduce their manifest-bound hashes on Windows and clean clones","configuration_action":"R282 adds exact .gitattributes rules without altering the normalized Git content","warning":WARNING},
    ];write_csv(OUT/"historical-errata-register.csv",errata)
    attempts=rows(CURVED/"failed-attempt-register.csv")
    attempts += [{"attempt_id":"R279-ATTEMPT-01","parts":"C06 L0","failure":"direct P2 sparse factorization exceeded practical desktop resource envelope","evidence":"884,739 prospective DOFs; >=180 s; 6,255..7,000 MB observed; interrupted cleanly","correction":"residual-controlled iterative and partitioned route","credit":"NONE","warning":WARNING},{"attempt_id":"R279-ATTEMPT-02","parts":"C06 P2C","failure":"direct P2 sparse factorization exceeded practical desktop resource envelope","evidence":"162,702 DOFs; >=225 s; 5,048 MB and climbing; interrupted cleanly","correction":"bounded direct cross-check at 41,139 DOFs plus iterative route","credit":"NONE","warning":WARNING}]
    write_csv(OUT/"failed-attempt-register.csv",attempts)
    inputs=[]
    for p,role in ((ROOT/"cad/hr-v0/generated/arm-architecture-p0.13-pad-pocket-stop/parts/MV0-C06_J2_positive_moving_striker_adapter.step","C06 STEP"),(ROOT/"cad/hr-v0/generated/arm-architecture-p0.13-pad-pocket-stop/parts/MV0-C07_J2_positive_fixed_catch_adapter.step","C07 STEP"),(ROOT/"tools/generate_hr_v0_j2_curved_tet10_prototype_p01.py","curved importer"),(ROOT/"tools/generate_hr_v0_j2_backend_crosscheck_p01.py","backend crosscheck"),(ROOT/"tools/generate_hr_v0_j2_stop_refinement_execution_p01.py","shared exact tagging/local mesh source"),(ROOT/".gitattributes","checkout byte-representation contract"),(ROOT/"mechanical/analysis/hr-v0-j2-numerical-backend-p0.1/analysis-status.json","immutable R281 status interpreted by erratum"),(ROOT/"mechanical/analysis/hr-v0-j2-numerical-backend-p0.1/method-register.csv","immutable R281 method register interpreted by erratum")):
        inputs.append({"input":p.relative_to(ROOT).as_posix(),"role":role,"sha256":sha(p),"bytes":p.stat().st_size,"warning":WARNING})
    write_csv(OUT/"exact-input-register.csv",inputs)
    holds=["Repair C07 curved Tet10 mesh until signed Jacobian orientation passes at frozen quadrature","Freeze exact CAD edge signatures for every split C06/C07/hole zone","Implement exact B-Rep distance/intersection membership and direct quadrature statistics","Execute resource-scaled L0-L3/L4 study with fixed domains and raw evidence bundles","Obtain independent acceptance of ACC-04 backend/reference evidence and residual-correction policy","Close H03 contact, H04 joined hardware/frame, dynamics, physical correlation and qualified capacity separately"]
    write_csv(OUT/"open-holds.csv",[{"hold_id":f"R282-H{i:02d}","hold":h,"state":"OPEN","effect":"R278-H02, selection, capacity and all work authority remain blocked","warning":WARNING} for i,h in enumerate(holds,1)])
    acceptance=[{"acceptance_id":"R281-ACC-01","criterion":"C06/C07 accepted multi-level execution","execution_state":"NOT EXECUTED","result":"OPEN"},{"acceptance_id":"R281-ACC-02","criterion":"curved geometry/order sensitivity","execution_state":"PROTOTYPE ONLY","result":"OPEN - C07 WRONG-SIGN JACOBIANS"},{"acceptance_id":"R281-ACC-03","criterion":"fixed zones/gauges/moment/GCI/singularity trends","execution_state":"PROTOCOL CORRECTED; NOT EXECUTED","result":"OPEN"},{"acceptance_id":"R281-ACC-04","criterion":"independent backend/reference verification and correction-policy acceptance","execution_state":"PROJECT-OWNED DIRECT/CG AND ANALYTIC PATCH EXECUTED","result":"NUMERICAL TESTS PASS; INDEPENDENT ACCEPTANCE OPEN"},{"acceptance_id":"R281-ACC-05","criterion":"H03/H04/dynamic/physical/qualified gates stay separate","execution_state":"ENFORCED","result":"OPEN"}]
    for r in acceptance:r["warning"]=WARNING
    write_csv(OUT/"acceptance-matrix.csv",acceptance)
    status={"identifier":IDENT,"round":"R282","date":"2026-08-12","historical_baseline_commit":HISTORICAL_BASELINE_COMMIT,"historical_r281_artifacts_mutated":False,"protocol_erratum_current":True,"prior_r279_protocol_sufficient_for_execution":False,"monolithic_l0_l3_executed":False,"backend_direct_cg_crosscheck_pass":cross["backend_crosscheck_pass"],"affine_patch_test_pass":cross["affine_patch_test_pass"],"r281_acc_04_independently_accepted":False,"c06_curved_import_screen_pass":True,"c07_curved_import_screen_pass":False,"curved_geometry_order_sensitivity_complete":False,"exact_zone_execution_complete":False,"raw_convergence_evidence_complete":False,"mesh_convergence_complete":False,"r278_h02_closed":False,"nonlinear_contact_complete":False,"joined_joint_complete":False,"selected":False,"capacity_established":False,"fabrication_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False,"warning":WARNING}
    (OUT/"analysis-status.json").write_text(json.dumps(status,indent=2)+"\n",encoding="utf-8")
    page=f"""<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>R282 J2 protocol correction</title><style>:root{{--navy:#082b55;--deep:#041a35;--gold:#f4b942;--paper:#f7fbff;--ink:#102a43;--line:#8ac8e8;--red:#9b1c1c}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:17px/1.55 system-ui,sans-serif}}header{{background:linear-gradient(135deg,var(--deep),var(--navy));color:white;padding:clamp(32px,6vw,72px) 20px}}header>div,main{{max-width:1240px;margin:auto}}main{{padding:30px 20px 80px}}h1{{font-size:clamp(36px,6vw,66px);line-height:1.08}}h2{{font-size:clamp(26px,3vw,40px)}}.warning{{background:var(--gold);color:#17243a;border:3px solid #805600;padding:16px;font-weight:900}}.stop{{background:white;border:3px solid var(--red);border-radius:14px;padding:20px;margin:24px 0}}.scroll{{overflow:auto;border:2px solid var(--line);border-radius:12px;background:white;margin-bottom:24px}}table{{border-collapse:collapse;width:100%;min-width:1000px}}th,td{{font-size:16px;padding:13px 14px;text-align:left;vertical-align:top;border-bottom:1px solid var(--line)}}th{{background:var(--navy);color:white}}@media(max-width:620px){{body{{font-size:16px}}main{{padding-inline:14px}}}}</style></head><body><header><div><p class='warning'>{WARNING}</p><p>R282 · {IDENT}</p><h1>H02 remains open. The execution protocol is now fail-closed.</h1><p>The prior global quality language was too broad, the physical zones and GCI rules were incomplete, and a monolithic L3 desktop run is not justified.</p></div></header><main><section class='stop'><h2>What the prototypes found</h2><p>C06 curved Tet10 transfer passes its signed-Jacobian prototype screen. C07 maps every quadratic edge but has 18 wrong-orientation quadrature Jacobians, so curved execution stops. Direct and iterative solvers agree on a deliberately coarse exact-CAD case, and both pass an analytic affine patch test. That verifies only the assembly/linear-algebra route.</p></section><h2>What R281 got wrong</h2>{table(errata)}<h2>Frozen protocol corrections</h2>{table(freeze)}<h2>Exact zones still to implement</h2>{table(zones)}<h2>Resource-scaled route</h2>{table(architecture)}<h2>Evidence</h2>{table(evidence)}<h2>Acceptance state</h2>{table(acceptance)}<h2>Open holds</h2>{table(rows(OUT/'open-holds.csv'))}</main></body></html>"""
    (OUT/"README.md").write_text(f"# {IDENT}\n\n> **{WARNING}**\n\nR282 corrects the R279 execution protocol and publishes bounded backend/curved-geometry prototypes. C07 curved Jacobians fail, so H02 remains open.\n",encoding="utf-8");(OUT/"index.html").write_text(page,encoding="utf-8");manifest(OUT);shutil.copytree(OUT,REL);manifest(REL)
    # Publish bounded subpackages without upgrading them to convergence evidence.
    for source,name in ((CURVED,"j2-curved-tet10-prototype-p0.1"),(XCHK,"j2-backend-crosscheck-p0.1")):
        manifest(source);target=ROOT/"release/hr-v0"/name
        if target.exists():shutil.rmtree(target)
        shutil.copytree(source,target);manifest(target)
    shutil.copytree(CFG0,CFG);current=rows(CFG/"current-configuration-map.csv");current.append({"record_id":"CFG-65","role":"R282 J2 fail-closed refinement erratum and method evidence","identifier":IDENT,"source_path":"release/hr-v0/j2-refinement-erratum-p0.1/analysis-status.json","configuration_state":"CURRENT PROTOCOL CORRECTION - H02 OPEN / C07 CURVED SCREEN FAIL","release_boundary":"exact zones, repaired curved mesh, resource-scaled L0-L3/L4, raw evidence, independent/qualified acceptance","warning":WARNING});write_csv(CFG/"current-configuration-map.csv",current)
    ch,ca=rows(CFG/"open-holds.csv"),rows(CFG/"acceptance-matrix.csv")
    for h in rows(OUT/"open-holds.csv"):
        ch.append({"hold_id":f"HOLD-{len(ch)+1:03d}","hold":f"{IDENT}: {h['hold']}","state":"OPEN","closure_evidence":"controlled numerical/physical evidence and independent/qualified acceptance","warning":WARNING});ca.append({"acceptance_id":f"ACC-{len(ca)+1:03d}","criterion":f"{IDENT}: {h['hold']}","execution_state":"NOT EXECUTED","result":"OPEN","evidence_uri":"","approver":"","warning":WARNING})
    write_csv(CFG/"open-holds.csv",ch);write_csv(CFG/"acceptance-matrix.csv",ca)
    cfg=json.loads((CFG/"package-status.json").read_text(encoding="utf-8"));cfg.update({"identifier":CFGID,"round":"R282","current_records":len(current),"open_holds":len(ch),"acceptance_rows":len(ca),"j2_refinement_erratum":IDENT,"j2_protocol_erratum_current":True,"j2_c07_curved_import_screen_pass":False,"j2_backend_crosscheck_project_owned_pass":True,"r281_acc_04_independently_accepted":False,"r278_h02_closed":False,"fabrication_authorized":False,"powered_testing_authorized":False,"motion_authorized":False,"energization_authorized":False,"safety_credit":False});(CFG/"package-status.json").write_text(json.dumps(cfg,indent=2)+"\n",encoding="utf-8")
    write_csv(CFG/"source-hash-register.csv",[{"source_path":r["source_path"],"sha256":sha(ROOT/r["source_path"]),"role":r["role"],"warning":WARNING} for r in current]);(CFG/"README.md").write_text(f"# {CFGID}\n\n> **{WARNING}**\n\nR282 indexes the current fail-closed J2 refinement erratum. H02 and every work authority remain open.\n",encoding="utf-8");shutil.copy2(OUT/"index.html",CFG/"index.html");manifest(CFG);shutil.copytree(CFG,CFGREL);manifest(CFGREL)
    # Human-facing documents and traceability.
    (ROOT/"docs/hr-v0-j2-refinement-erratum-p0.1.md").write_text(f"# HR-V0 J2 refinement erratum P0.1\n\n> **{WARNING}**\n\nR282 supersedes R279 only for execution detail. It freezes the datum, probes, zones, SICN histogram, metric-specific effective mesh size, unequal-grid GCI rules, exact B-Rep membership, direct-quadrature statistics, raw-evidence bundle and resource-scaled execution route. It also adds four exact checkout-EOL rules needed to reproduce R281's manifest-bound Windows working bytes without changing normalized Git content.\n\nC06 Tet10-to-MeshTet2 mapping passes a bounded signed-Jacobian screen. C07 maps all 26,209 quadratic edges but has 18 wrong-orientation quadrature Jacobians, so curved execution is blocked. The coarse direct/CG comparison and analytic affine patch pass, but R281-ACC-04 remains open pending independent acceptance. H02 remains open.\n\n[Interactive R282 guide](../release/hr-v0/j2-refinement-erratum-p0.1/index.html)\n",encoding="utf-8")
    (ROOT/"docs/reviews/2026-08-12-r282-independent-review-request.md").write_text(f"# R282 independent review request\n\n> **{WARNING}**\n\nPlease audit `{IDENT}` for: the frozen part-local origin moment convention; exact C07 probes; fixed SICN bins; exact B-Rep zone identities; metric-specific effective h; generalized unequal-grid GCI orientation; direct quadrature statistics; raw evidence requirements; resource-scaled submodel/HPC route; Tet10 edge mapping; signed Jacobian screen; coarse direct/CG agreement; affine elasticity patch; and explicit non-closure of R281-ACC-04 and H02.\n",encoding="utf-8")
    (ROOT/"docs/reviews/2026-08-12-r282-validation-record.md").write_text(f"# R282 validation draft\n\n> **{WARNING}**\n\nGenerated and checker-verified project-owned evidence: C06 curved mapping 18,351/18,351 edges and zero wrong-orientation quadrature Jacobians; C07 mapping 26,209/26,209 edges and **18 wrong-orientation quadrature Jacobians (fail)**; coarse direct/CG solution difference 7.382440e-13, energy difference 1.086597e-12, displacement difference 6.631311e-13; analytic affine-patch DOF errors 1.664105e-16 direct and 1.316926e-13 CG. Independent review, exact-zone implementation, raw convergence execution, H02 and all work authority remain open.\n\nBrowser DOM QA passed. At 1440 x 900, body text is 17 px, minimum functional text is 16 px, there is no root overflow, and all seven table wrappers fit. At 390 x 844 (375 px client width), body/minimum text is 16 px, there is no root overflow, and all seven tables scroll internally. The warning, H02-open statement and `What R281 got wrong` section are visible.\n",encoding="utf-8")
    hand=ROOT/"docs/handoff-current.md";old=hand.read_text(encoding="utf-8");prefix=f"R282 J2 refinement erratum: **`{IDENT}` corrects the incomplete R279 execution details. C07 curved Tet10 geometry currently fails signed-Jacobian screening; H02, capacity and all physical work remain blocked.**\n\n";old=old.replace(prefix,"");hand.write_text(prefix+old,encoding="utf-8")
    ledger=ROOT/"docs/review-ledger.md";txt=ledger.read_text(encoding="utf-8").replace("Two hundred eighty-one rounds are complete (R01-R281).","Two hundred eighty-two rounds are complete (R01-R282).")
    if "| R282 |" not in txt:txt=txt.rstrip()+f"\n| R282 | 2026-08-12 | J2 refinement protocol erratum, curved geometry prototype and backend references | Codex project-owned correction; independent review requested | R281 established bounded linear-geometry P2-displacement feasibility but overstated C07 quality scope and left datum/zones/GCI/raw evidence incomplete. | Protocol frozen; C06 curved import screen passes; C07 fails 18 wrong-orientation quadrature Jacobians; direct/CG and affine patch tests pass project-owned gates. H02 and all authority remain open. | `docs/hr-v0-j2-refinement-erratum-p0.1.md`; `release/hr-v0/j2-refinement-erratum-p0.1/`; `configuration/hr-v0-config-reconciliation-p0.46/` |\n"
    ledger.write_text(txt,encoding="utf-8")
    readme=ROOT/"README.md";txt=readme.read_text(encoding="utf-8");links="- [R282 J2 refinement erratum](docs/hr-v0-j2-refinement-erratum-p0.1.md)\n- [R282 independent review request](docs/reviews/2026-08-12-r282-independent-review-request.md)\n- [R282 validation draft](docs/reviews/2026-08-12-r282-validation-record.md)\n- [Interactive R282 fail-closed guide](release/hr-v0/j2-refinement-erratum-p0.1/index.html)\n- [Interactive configuration reconciliation P0.46](release/hr-v0/configuration-reconciliation-p0.46/index.html)\n"
    txt=txt.replace(links,"").replace("## Start here\n\n","## Start here\n\n"+links).replace("Two hundred eighty-one rounds are complete: R01-R281.","Two hundred eighty-two rounds are complete: R01-R282.");readme.write_text(txt,encoding="utf-8")
    cm=ROOT/"docs/configuration-management.md";ct=cm.read_text(encoding="utf-8");line=f"R282 adds `{IDENT}` as the current J2 refinement execution correction and `{CFGID}` as the configuration index only. It corrects R281's global-quality overstatement, records the C07 curved-Jacobian failure, and leaves H02 and all work authority open.";ct=ct.replace("\n"+line,"");cm.write_text(ct.rstrip()+"\n\n"+line+"\n",encoding="utf-8")
    import generate_hr_v0_collapse_envelope as g;g.write_generated_source_manifest();print(f"Published R282 {IDENT}; C07 curved screen fails and H02 remains open");return 0
if __name__=="__main__":raise SystemExit(main())
